# Generated By: Cursor (Claude Sonnet 4.5)
# GitHub Pull Request Metrics Tool Makefile
# ==========================================

# Include common variables first
include make/common.mk

# Include modular makefiles
include make/env.mk
include make/test.mk
include make/lint.mk

.DEFAULT_GOAL := all
.PHONY: help all all-data reprocess

all: test-unit coverage lint format ## Run all checks (default target)

help: ## Display this help message
	@echo "GitHub Pull Request Metrics Tool"
	@echo "================================="
	@echo ""
	@echo "Available targets:"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

update: ## Fetch/update PR data for all tracked repositories
	@GITHUB_TOKEN=$(gh auth token) gh-pr-metrics --workers 16 --update-all

reprocess: ## Reprocess cached PR data with current config (no API calls)
	@gh-pr-metrics --reprocess

all-data: ## Merge per-repo CSVs into all-data.csv and all-data-rollup.csv
	@python utility/create-single-csv.py data/