# Generated By: Cursor (Claude Sonnet 4.5)
# GitHub Pull Request Metrics Tool Makefile
# ==========================================

# Include common variables first
include make/common.mk

# Include modular makefiles
include make/env.mk
include make/test.mk
include make/lint.mk

.DEFAULT_GOAL := help
.PHONY: help

help: ## Display this help message
	@echo "GitHub Pull Request Metrics Tool"
	@echo "================================="
	@echo ""
	@echo "Available targets:"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)
