# Generated By: Cursor (Claude Sonnet 4.5)
"""Pytest configuration and fixtures for all tests."""

import pytest


@pytest.fixture(autouse=True)
def isolate_state_file(tmp_path, monkeypatch):
    """
    Automatically isolate state file for ALL tests.

    Prevents tests from touching the real ~/.gh-pr-metrics-state.yaml file.
    Each test gets its own isolated state file in a temp directory.
    """
    test_state_file = tmp_path / "test_state.yaml"

    # Patch the STATE_FILE constant before any code uses it
    import gh_pr_metrics

    monkeypatch.setattr(gh_pr_metrics, "STATE_FILE", test_state_file)

    # Recreate state_manager with the patched STATE_FILE
    gh_pr_metrics.state_manager = gh_pr_metrics.StateManager(logger=gh_pr_metrics.logger)

    yield test_state_file

    # Cleanup
    if test_state_file.exists():
        test_state_file.unlink()


@pytest.fixture(autouse=True)
def reset_quota_manager():
    """
    Automatically reset quota_manager to clean state for ALL tests.

    Prevents tests from being affected by depleted quota state from
    previous tests. Each test starts with fresh quota.
    """
    import gh_pr_metrics

    # Reset quota manager to fresh state (high quota)
    gh_pr_metrics.quota_manager._remaining = 5000
    gh_pr_metrics.quota_manager._limit = 5000
    gh_pr_metrics.quota_manager._reset = 1699999999  # Some future timestamp

    yield

    # Tests should mock rate_limit endpoint, but reset anyway for safety
    gh_pr_metrics.quota_manager._remaining = 5000
    gh_pr_metrics.quota_manager._limit = 5000
    gh_pr_metrics.quota_manager._reset = 1699999999
