# Generated By: Cursor (Claude Sonnet 4.5)
"""
Basic integration tests for gh-pr-metrics.

Tests end-to-end workflows with minimal external dependencies.
Uses public repositories and mock data to avoid rate limiting.
"""

import sys
from datetime import datetime, timezone
from pathlib import Path

import pytest

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
import gh_pr_metrics  # noqa: E402
from github_api import QuotaManager  # noqa: E402


class TestBasicWorkflow:
    """Test basic workflow without actual GitHub API calls."""

    def test_csv_manager_write_and_read(self, tmp_path):
        """Test CSV manager can write and read metrics."""
        csv_manager = gh_pr_metrics.CSVManager()
        output_file = tmp_path / "test_metrics.csv"

        # Create sample metrics
        metrics = [
            {
                "pr_number": 1,
                "title": "Test PR 1",
                "author": "user1",
                "created_at": "2024-01-01T00:00:00Z",
                "ready_for_review_at": "2024-01-01T01:00:00Z",
                "merged_at": "2024-01-02T00:00:00Z",
                "closed_at": "2024-01-02T00:00:00Z",
                "days_open": 1.0,
                "days_in_review": 0.96,
                "total_comment_count": 5,
                "non_ai_bot_comment_count": 3,
                "ai_bot_comment_count": 2,
                "non_ai_bot_login_names": "bot1,bot2",
                "ai_bot_login_names": "cursor[bot]",
                "changes_requested_count": 1,
                "unique_change_requesters": 1,
                "approval_count": 2,
                "status": "merged",
                "url": "https://github.com/owner/repo/pull/1",
                "errors": "",
                "lines_added": 100,
                "lines_deleted": 50,
                "files_changed": 3,
                "total_line_changes": 150,
            }
        ]

        # Write metrics
        csv_manager.write_csv(metrics, str(output_file))

        # Verify file exists
        assert output_file.exists()

        # Read metrics back
        existing_data = csv_manager.read_csv(str(output_file))

        assert len(existing_data) == 1
        assert existing_data[1]["title"] == "Test PR 1"
        assert existing_data[1]["author"] == "user1"

    def test_csv_manager_merge_mode(self, tmp_path):
        """Test CSV manager merge mode updates existing PRs."""
        csv_manager = gh_pr_metrics.CSVManager()
        output_file = tmp_path / "test_metrics.csv"

        # Write initial metrics
        initial_metrics = [
            {
                "pr_number": 1,
                "title": "Old Title",
                "author": "user1",
                "created_at": "2024-01-01T00:00:00Z",
                "ready_for_review_at": "2024-01-01T01:00:00Z",
                "merged_at": "",
                "closed_at": "",
                "days_open": 1.0,
                "days_in_review": 0.96,
                "total_comment_count": 5,
                "non_ai_bot_comment_count": 3,
                "ai_bot_comment_count": 2,
                "non_ai_bot_login_names": "bot1",
                "ai_bot_login_names": "cursor[bot]",
                "changes_requested_count": 1,
                "unique_change_requesters": 1,
                "approval_count": 2,
                "status": "open",
                "url": "https://github.com/owner/repo/pull/1",
                "errors": "",
                "lines_added": 100,
                "lines_deleted": 50,
                "files_changed": 3,
                "total_line_changes": 150,
            }
        ]
        csv_manager.write_csv(initial_metrics, str(output_file))

        # Update with new data (PR now merged)
        updated_metrics = [
            {
                "pr_number": 1,
                "title": "New Title",  # Updated
                "author": "user1",
                "created_at": "2024-01-01T00:00:00Z",
                "ready_for_review_at": "2024-01-01T01:00:00Z",
                "merged_at": "2024-01-02T00:00:00Z",  # Updated
                "closed_at": "2024-01-02T00:00:00Z",  # Updated
                "days_open": 1.0,
                "days_in_review": 0.96,
                "total_comment_count": 7,  # Updated
                "non_ai_bot_comment_count": 3,
                "ai_bot_comment_count": 4,  # Updated
                "non_ai_bot_login_names": "bot1",
                "ai_bot_login_names": "cursor[bot]",
                "changes_requested_count": 1,
                "unique_change_requesters": 1,
                "approval_count": 3,  # Updated
                "status": "merged",  # Updated
                "url": "https://github.com/owner/repo/pull/1",
                "errors": "",
                "lines_added": 100,
                "lines_deleted": 50,
                "files_changed": 3,
                "total_line_changes": 150,
            }
        ]

        csv_manager.write_csv(updated_metrics, str(output_file), merge_mode=True)

        # Verify merged data
        final_data = csv_manager.read_csv(str(output_file))
        assert len(final_data) == 1  # Still only one PR
        assert final_data[1]["title"] == "New Title"
        assert final_data[1]["status"] == "merged"
        assert final_data[1]["approval_count"] == "3"

    def test_state_manager_workflow(self, tmp_path):
        """Test state manager save and load workflow."""
        state_file = tmp_path / "test_state.yaml"
        state_manager = gh_pr_metrics.StateManager(state_file_path=state_file)

        # Update repo state
        now = datetime.now(timezone.utc)
        state_manager.update_repo("owner", "repo", now, "/path/to/metrics.csv")

        # Verify state file was created
        assert state_file.exists()

        # Load and verify state
        repo_state = state_manager.get_repo_state("owner", "repo")
        assert repo_state is not None
        assert repo_state["csv_file"] == "/path/to/metrics.csv"
        assert isinstance(repo_state["timestamp"], datetime)

    def test_config_ai_bot_detection_workflow(self):
        """Test AI bot detection with various scenarios."""
        config_dict = {
            "ai_bots": {
                "always": ["cursor\\[bot\\]", "copilot\\[bot\\]"],
                "conditional": [
                    {
                        "name": "github-actions\\[bot\\]",
                        "content_patterns": ["Code Review Summary"],
                        "match_any": True,
                    }
                ],
            }
        }
        config = gh_pr_metrics.Config(config_dict)

        # Test always-AI bots
        assert config.is_ai_bot("cursor[bot]", "") is True
        assert config.is_ai_bot("copilot[bot]", "") is True

        # Test conditional bot with matching content
        assert config.is_ai_bot("github-actions[bot]", "Code Review Summary: All good") is True

        # Test conditional bot without matching content
        assert config.is_ai_bot("github-actions[bot]", "Deployment complete") is False

        # Test non-AI bot
        assert config.is_ai_bot("dependabot[bot]", "") is False

    def test_quota_manager_tracking(self):
        """Test quota manager tracks rate limits correctly."""
        quota_manager = QuotaManager()

        # Simulate API response headers
        headers = {
            "X-RateLimit-Remaining": "4500",
            "X-RateLimit-Limit": "5000",
            "X-RateLimit-Reset": "1699999999",
        }

        quota_manager.update_from_headers(headers)

        remaining, limit, reset = quota_manager.get_current_quota()
        assert remaining == 4500
        assert limit == 5000
        assert reset == 1699999999

        # Test max PRs calculation
        max_prs = quota_manager.calculate_max_prs()
        assert max_prs > 0  # Should be able to process some PRs

    def test_output_pattern_expansion(self):
        """Test output pattern expansion with placeholders."""
        pattern = "data/{owner}-{repo}.csv"
        expanded = gh_pr_metrics.expand_output_pattern(pattern, "ansible", "awx")
        assert expanded == "data/ansible-awx.csv"

        # Test with only owner
        pattern2 = "metrics/{owner}.csv"
        expanded2 = gh_pr_metrics.expand_output_pattern(pattern2, "microsoft", "vscode")
        assert expanded2 == "metrics/microsoft.csv"

        # Test with only repo
        pattern3 = "{repo}_metrics.csv"
        expanded3 = gh_pr_metrics.expand_output_pattern(pattern3, "google", "chrome")
        assert expanded3 == "chrome_metrics.csv"

    def test_timestamp_parsing(self):
        """Test timestamp parsing handles various formats."""
        # ISO 8601 with timezone
        dt1 = gh_pr_metrics.parse_timestamp("2024-01-01T00:00:00Z")
        assert isinstance(dt1, datetime)
        assert dt1.tzinfo is not None

        # ISO 8601 without timezone (should add UTC)
        dt2 = gh_pr_metrics.parse_timestamp("2024-01-01T00:00:00")
        assert isinstance(dt2, datetime)
        assert dt2.tzinfo is not None

        # RFC 3339
        dt3 = gh_pr_metrics.parse_timestamp("2024-01-01 00:00:00+00:00")
        assert isinstance(dt3, datetime)
        assert dt3.tzinfo is not None

        # Invalid timestamp
        with pytest.raises(ValueError):
            gh_pr_metrics.parse_timestamp("invalid-timestamp")

    def test_pr_status_determination(self):
        """Test PR status determination logic."""
        # Draft PR
        draft_pr = {"draft": True, "merged_at": None, "state": "open"}
        assert gh_pr_metrics.determine_pr_status(draft_pr) == "draft"

        # Merged PR
        merged_pr = {"draft": False, "merged_at": "2024-01-01T00:00:00Z", "state": "closed"}
        assert gh_pr_metrics.determine_pr_status(merged_pr) == "merged"

        # Closed (not merged) PR
        closed_pr = {"draft": False, "merged_at": None, "state": "closed"}
        assert gh_pr_metrics.determine_pr_status(closed_pr) == "closed"

        # Open PR
        open_pr = {"draft": False, "merged_at": None, "state": "open"}
        assert gh_pr_metrics.determine_pr_status(open_pr) == "open"


class TestEndToEndCSVWorkflow:
    """Test complete CSV workflow from write to update."""

    def test_full_csv_lifecycle(self, tmp_path):
        """Test complete CSV lifecycle: create, update, merge."""
        csv_manager = gh_pr_metrics.CSVManager()
        output_file = tmp_path / "lifecycle.csv"

        # Step 1: Initial write
        initial_prs = [
            self._create_pr_metric(1, "open"),
            self._create_pr_metric(2, "open"),
        ]
        csv_manager.write_csv(initial_prs, str(output_file))

        # Step 2: Verify initial state
        data = csv_manager.read_csv(str(output_file))
        assert len(data) == 2

        # Step 3: Update PR 1 (merged)
        updated_pr1 = self._create_pr_metric(1, "merged")
        updated_pr1["merged_at"] = "2024-01-02T00:00:00Z"
        csv_manager.write_csv([updated_pr1], str(output_file), merge_mode=True)

        # Step 4: Verify merge
        data = csv_manager.read_csv(str(output_file))
        assert len(data) == 2  # Still 2 PRs
        assert data[1]["status"] == "merged"
        assert data[2]["status"] == "open"  # PR 2 unchanged

        # Step 5: Add new PR 3
        new_pr3 = self._create_pr_metric(3, "open")
        csv_manager.write_csv([new_pr3], str(output_file), merge_mode=True)

        # Step 6: Verify addition
        data = csv_manager.read_csv(str(output_file))
        assert len(data) == 3  # Now 3 PRs
        assert data[1]["status"] == "merged"
        assert data[2]["status"] == "open"
        assert data[3]["status"] == "open"

    def _create_pr_metric(self, pr_number: int, status: str) -> dict:
        """Helper to create a PR metric dict."""
        return {
            "pr_number": pr_number,
            "title": f"PR {pr_number}",
            "author": "testuser",
            "created_at": "2024-01-01T00:00:00Z",
            "ready_for_review_at": "2024-01-01T01:00:00Z",
            "merged_at": "" if status != "merged" else "2024-01-02T00:00:00Z",
            "closed_at": "" if status == "open" else "2024-01-02T00:00:00Z",
            "days_open": 1.0,
            "days_in_review": 0.96,
            "total_comment_count": 0,
            "non_ai_bot_comment_count": 0,
            "ai_bot_comment_count": 0,
            "non_ai_bot_login_names": "",
            "ai_bot_login_names": "",
            "changes_requested_count": 0,
            "unique_change_requesters": 0,
            "approval_count": 0,
            "status": status,
            "url": f"https://github.com/owner/repo/pull/{pr_number}",
            "errors": "",
            "lines_added": 10,
            "lines_deleted": 5,
            "files_changed": 1,
            "total_line_changes": 15,
        }
