#!/usr/bin/env python3
# Generated By: Cursor (Claude Sonnet 4.5)
"""
Init Command Module

Initializes repository tracking in the state file.
"""

import argparse

from .base_command import BaseCommand


class InitCommand(BaseCommand):
    """
    Initialize repository tracking.

    Creates state file entries for repositories without fetching data.
    Can initialize a single repo or all repos for an owner.
    """

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        """Add init-specific arguments."""
        parser.add_argument(
            "--owner",
            required=True,
            help="Repository owner (organization or user)",
        )
        parser.add_argument(
            "--repo",
            help="Repository name (optional - omit to initialize all owner repos)",
        )
        parser.add_argument(
            "--start",
            required=True,
            help="Start date for tracking (ISO 8601 format, e.g., 2024-01-01)",
        )
        parser.add_argument(
            "--output",
            help="CSV output file pattern (supports {owner} and {repo} placeholders)",
        )

    def run(self, args: argparse.Namespace) -> int:
        """
        Execute init command.

        Args:
            args: Parsed arguments

        Returns:
            Exit code (0 for success, non-zero for failure)
        """
        owner = args.owner
        repo = args.repo
        start_str = args.start
        output_pattern = args.output

        # Parse start date
        try:
            from gh_pr_metrics import parse_timestamp

            start_date = parse_timestamp(start_str)
        except ValueError as e:
            self.logger.error("Invalid start date: %s", e)
            return 1

        # Get list of repos to initialize
        if repo:
            # Single repo mode
            repos_to_init = [repo]
            self.logger.info("Initializing repository: %s/%s", owner, repo)
        else:
            # All owner repos mode
            self.logger.info("Fetching all repositories for owner: %s", owner)
            try:
                all_repos = self.github_client.list_repos(owner)
                repos_to_init = [r["name"] for r in all_repos]
                self.logger.info("Found %d repositories for %s", len(repos_to_init), owner)
            except Exception as e:
                self.logger.error("Failed to list repositories for %s: %s", owner, e)
                return 1

        # Initialize each repo
        initialized_count = 0
        skipped_count = 0

        for repo_name in repos_to_init:
            # Check if already initialized
            existing_state = self.state_manager.get_repo_state(owner, repo_name)
            if existing_state and existing_state.get("timestamp"):
                self.logger.info("Skipping %s/%s (already initialized)", owner, repo_name)
                skipped_count += 1
                continue

            # Determine CSV file path
            csv_file = None
            if output_pattern:
                # Expand pattern with placeholders
                from gh_pr_metrics import expand_output_pattern

                csv_file = expand_output_pattern(output_pattern, owner, repo_name)
            elif self.config.output_pattern:
                # Use config pattern
                from gh_pr_metrics import expand_output_pattern

                csv_file = expand_output_pattern(self.config.output_pattern, owner, repo_name)

            # Create state entry
            self.state_manager.update_repo(owner, repo_name, start_date, csv_file)
            self.logger.info(
                "Initialized %s/%s (start: %s, output: %s)",
                owner,
                repo_name,
                start_date.isoformat(),
                csv_file or "(not set)",
            )
            initialized_count += 1

        # Summary
        self.logger.info(
            "Initialization complete: %d initialized, %d skipped",
            initialized_count,
            skipped_count,
        )

        return 0
