#!/usr/bin/env python3
# Generated By: Cursor (Claude Sonnet 4.5)
"""
Logging Management Module

Wraps standard logging to inject API quota status into all log messages.
"""

import logging


class LoggingManager:
    """
    Manages application logging with quota-aware prefixes.

    Wraps standard logging to inject API quota status into all log messages.
    """

    def __init__(self, quota_manager):
        """Initialize logging manager with reference to quota manager."""
        self._quota_manager = quota_manager

    def info(self, msg: str, *args, **kwargs) -> None:
        """Log INFO with API quota prefix."""
        logging.info(f"{self._quota_manager.get_quota_prefix()} {msg}", *args, **kwargs)

    def warning(self, msg: str, *args, **kwargs) -> None:
        """Log WARNING with API quota prefix."""
        logging.warning(f"{self._quota_manager.get_quota_prefix()} {msg}", *args, **kwargs)

    def error(self, msg: str, *args, **kwargs) -> None:
        """Log ERROR with API quota prefix."""
        logging.error(f"{self._quota_manager.get_quota_prefix()} {msg}", *args, **kwargs)

    def debug(self, msg: str, *args, **kwargs) -> None:
        """Log DEBUG with API quota prefix."""
        logging.debug(f"{self._quota_manager.get_quota_prefix()} {msg}", *args, **kwargs)
