# Generated By: Claude Code (Claude Opus 4.6)
# Standard test-* collection (see build/makefile.md).

.PHONY: test-unit test-coverage test-format test-lint test-typecheck test-complexity

test-unit: install-dev ## Run pytest
	@$(PYTHON) -m pytest tests/ -v $(ARGS)
	@printf "$(GREEN)✅ Unit tests completed$(RESET)\n"

test-coverage: install-dev ## Run pytest with coverage threshold
	@$(PYTHON) -m pytest tests/ --cov=src --cov-report=term --cov-fail-under=$(COVERAGE_THRESHOLD) $(ARGS)
	@printf "$(GREEN)✅ Coverage check passed$(RESET)\n"

test-format: install-dev ## Check formatting (exits non-zero if changes needed)
	@$(PYTHON) -m black --check src/ tests/ utility/
	@printf "$(GREEN)✅ Format check passed$(RESET)\n"

test-lint: install-dev ## Lint with flake8
	@$(PYTHON) -m flake8 --max-line-length=88 --extend-ignore=E203,W503,E501 src/ tests/ utility/
	@printf "$(GREEN)✅ Linting complete$(RESET)\n"

test-typecheck: install-dev ## Type check with mypy
	@$(PYTHON) -m mypy src/
	@printf "$(GREEN)✅ Type checking complete$(RESET)\n"

test-complexity: install-dev ## Check cyclomatic complexity with xenon
	@$(PYTHON) -m xenon src/ --max-absolute B --max-modules B --max-average A
	@printf "$(GREEN)✅ Complexity check passed$(RESET)\n"
