# Generated By: Claude Code (Claude Sonnet 4.5)
"""Utility functions for gh-pr-metrics."""

from dateutil import parser as date_parser


def format_timestamp_local(timestamp) -> str:
    """
    Format timestamp for log messages in local time with timezone offset.

    Ensures all timestamps in log messages match the log statement timezone.
    Format: YYYY-MM-DD HH:MM:SS±HHMM

    Args:
        timestamp: datetime object, ISO string, or string timestamp

    Returns:
        Formatted timestamp string in local time with timezone offset
    """
    if isinstance(timestamp, str):
        # Parse ISO string to datetime
        dt = date_parser.parse(timestamp)
    else:
        dt = timestamp

    # Convert to local time
    local_dt = dt.astimezone()

    # Format: YYYY-MM-DD HH:MM:SS±HHMM
    return local_dt.strftime("%Y-%m-%d %H:%M:%S%z")
