# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for pull request processing logic."""

import json

import gh_pr_metrics


class TestPRStatusDetermination:
    """Test PR status determination logic."""

    def test_determine_draft_status(self):
        """Test identifying draft PRs."""
        pr = {"draft": True, "state": "open", "merged_at": None}
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "draft"

    def test_determine_merged_status(self, requests_mock, default_config):
        """Test identifying merged PRs and extracting merge timestamp."""
        pr = {
            "number": 1,
            "title": "Merged PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "merged_at": "2024-01-05T12:00:00Z",
            "closed_at": "2024-01-05T12:00:00Z",
            "created_at": "2024-01-01T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Test status determination
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "merged"

        # Test full PR processing extracts timestamps
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(reviews_url, json=[])

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)
        assert result["merged_at"] == "2024-01-05T12:00:00Z"
        assert result["closed_at"] == "2024-01-05T12:00:00Z"
        assert result["status"] == "merged"

    def test_determine_closed_status(self, requests_mock, default_config):
        """Test identifying closed (not merged) PRs and extracting close timestamp."""
        pr = {
            "number": 2,
            "title": "Closed PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "merged_at": None,
            "closed_at": "2024-01-10T15:30:00Z",
            "created_at": "2024-01-08T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/2",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/2/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/2/comments",
        }

        # Test status determination
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "closed"

        # Test full PR processing extracts timestamps
        events_url = "https://api.github.com/repos/owner/repo/issues/2/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/2/reviews"
        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(reviews_url, json=[])

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)
        assert result["merged_at"] == ""  # Not merged
        assert result["closed_at"] == "2024-01-10T15:30:00Z"
        assert result["status"] == "closed"

    def test_determine_open_status(self):
        """Test identifying open PRs."""
        pr = {"draft": False, "state": "open", "merged_at": None}
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "open"


class TestGetReadyForReviewFromEvents:
    """Test get_ready_for_review_from_events pure logic."""

    def test_no_events(self):
        """Returns created_at when no events."""
        result = gh_pr_metrics.get_ready_for_review_from_events(
            [], "2024-01-01T00:00:00Z"
        )
        assert result == "2024-01-01T00:00:00Z"

    def test_no_ready_events(self):
        """Returns created_at when no ready_for_review events."""
        events = [
            {"event": "labeled", "created_at": "2024-01-02T00:00:00Z"},
        ]
        result = gh_pr_metrics.get_ready_for_review_from_events(
            events, "2024-01-01T00:00:00Z"
        )
        assert result == "2024-01-01T00:00:00Z"

    def test_single_ready_event(self):
        """Returns ready_for_review timestamp."""
        events = [
            {"event": "ready_for_review", "created_at": "2024-01-03T00:00:00Z"},
        ]
        result = gh_pr_metrics.get_ready_for_review_from_events(
            events, "2024-01-01T00:00:00Z"
        )
        assert result == "2024-01-03T00:00:00Z"

    def test_multiple_ready_events_uses_last(self):
        """Returns the last ready_for_review timestamp."""
        events = [
            {"event": "ready_for_review", "created_at": "2024-01-02T00:00:00Z"},
            {"event": "convert_to_draft", "created_at": "2024-01-03T00:00:00Z"},
            {"event": "ready_for_review", "created_at": "2024-01-04T00:00:00Z"},
        ]
        result = gh_pr_metrics.get_ready_for_review_from_events(
            events, "2024-01-01T00:00:00Z"
        )
        assert result == "2024-01-04T00:00:00Z"

    def test_none_entries_filtered(self):
        """Handles None entries in events list."""
        events = [
            None,
            {"event": "ready_for_review", "created_at": "2024-01-02T00:00:00Z"},
            None,
        ]
        result = gh_pr_metrics.get_ready_for_review_from_events(
            events, "2024-01-01T00:00:00Z"
        )
        assert result == "2024-01-02T00:00:00Z"


class TestFetchAndNormalizeTimelineEvents:
    """Test fetch_and_normalize_timeline_events."""

    def test_normalizes_events(self, requests_mock):
        """Filters None, extracts event and created_at."""
        from github_api import GitHubClient

        client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )
        requests_mock.get(
            "https://api.github.com/repos/o/r/issues/1/events",
            json=[
                None,
                {
                    "event": "labeled",
                    "created_at": "2024-01-01T00:00:00Z",
                    "extra": "ignored",
                },
                None,
                {
                    "event": "ready_for_review",
                    "created_at": "2024-01-02T00:00:00Z",
                },
            ],
        )

        result = gh_pr_metrics.fetch_and_normalize_timeline_events(client, "o", "r", 1)

        assert len(result) == 2
        assert result[0] == {
            "event": "labeled",
            "created_at": "2024-01-01T00:00:00Z",
        }
        assert result[1] == {
            "event": "ready_for_review",
            "created_at": "2024-01-02T00:00:00Z",
        }

    def test_empty_events(self, requests_mock):
        """Returns empty list when no events."""
        from github_api import GitHubClient

        client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )
        requests_mock.get(
            "https://api.github.com/repos/o/r/issues/1/events",
            json=[],
        )

        result = gh_pr_metrics.fetch_and_normalize_timeline_events(client, "o", "r", 1)
        assert result == []

    def test_api_error_propagates(self, requests_mock):
        """GitHubAPIError is not caught — callers handle it."""
        from github_api import GitHubClient, GitHubAPIError

        client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )
        requests_mock.get(
            "https://api.github.com/repos/o/r/issues/1/events",
            status_code=500,
        )

        import pytest

        with pytest.raises(GitHubAPIError):
            gh_pr_metrics.fetch_and_normalize_timeline_events(client, "o", "r", 1)


class TestReadyForReviewTime:
    """Test ready for review timestamp determination."""

    def test_ready_for_review_never_draft(self, requests_mock, default_config):
        """Test PR that was never a draft."""
        # Initialize github_client
        from github_api import GitHubClient

        gh_pr_metrics.github_client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )

        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return no ready_for_review events
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(events_url, json=[])

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-01T00:00:00Z"

    def test_ready_for_review_with_event(self, requests_mock, default_config):
        """Test PR that was converted from draft."""
        # Initialize github_client
        from github_api import GitHubClient

        gh_pr_metrics.github_client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )

        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return ready_for_review event
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(
            events_url,
            json=[{"event": "ready_for_review", "created_at": "2024-01-02T00:00:00Z"}],
        )

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-02T00:00:00Z"

    def test_ready_for_review_with_none_entries(self, requests_mock, default_config):
        """Test PR timeline events containing None entries (deleted/removed events)."""
        # Initialize github_client
        from github_api import GitHubClient

        gh_pr_metrics.github_client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )

        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return a mix of None and valid events
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(
            events_url,
            json=[
                None,
                {"event": "labeled", "created_at": "2024-01-01T12:00:00Z"},
                None,
                {"event": "ready_for_review", "created_at": "2024-01-02T00:00:00Z"},
                None,
            ],
        )

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-02T00:00:00Z"

    def test_ready_for_review_ghost_user_in_reviews(
        self, requests_mock, default_config
    ):
        """Test PR with ghost user (deleted account) in reviews doesn't crash."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser", "type": "User"},
            "draft": False,
            "state": "open",
            "merged_at": None,
            "closed_at": None,
            "created_at": "2024-01-01T00:00:00Z",
            "updated_at": "2024-01-02T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API responses with ghost user (null user)
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"

        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            reviews_url,
            json=[
                {
                    "id": 123456,
                    "user": {"login": "realuser", "type": "User"},
                    "state": "APPROVED",
                    "body": "LGTM",
                    "submitted_at": "2024-01-02T00:00:00Z",
                },
                {
                    "id": 123457,
                    "user": None,  # Ghost user (deleted account)
                    "state": "APPROVED",
                    "body": "",
                    "submitted_at": "2024-01-02T05:00:00Z",
                },
            ],
        )

        # Should not crash
        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        # Verify basic fields are present
        assert result["pr_number"] == 1
        assert result["status"] == "open"

    def test_ready_for_review_api_error(self, requests_mock, default_config):
        """Test handling API errors when fetching events."""
        # Initialize github_client
        from github_api import GitHubClient

        gh_pr_metrics.github_client = GitHubClient(
            "fake_token", gh_pr_metrics.quota_manager, gh_pr_metrics.logger
        )

        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return error
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(events_url, status_code=500)

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        # Should fall back to created_at
        assert result == "2024-01-01T00:00:00Z"


class TestCommentCounting:
    """Test comment counting logic."""

    def test_count_comments_no_comments(self, requests_mock, default_config):
        """Test counting when there are no comments."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = (
            gh_pr_metrics.count_comments(pr, "owner", "repo", None, default_config)
        )
        assert total == 0
        assert non_ai_bot == 0
        assert ai_bot == 0
        assert non_ai_bot_names == ""
        assert ai_bot_names == ""

    def test_count_comments_with_regular_comments(self, requests_mock, default_config):
        """Test counting regular comments."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "User", "login": "user1"}},
                {"user": {"type": "User", "login": "user2"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"],
            json=[{"user": {"type": "User", "login": "user3"}}],
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = (
            gh_pr_metrics.count_comments(pr, "owner", "repo", None, default_config)
        )
        assert total == 3
        assert non_ai_bot == 0
        assert ai_bot == 0
        assert non_ai_bot_names == ""
        assert ai_bot_names == ""

    def test_count_comments_with_bot_comments(self, requests_mock, default_config):
        """Test counting bot comments separately."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "Bot", "login": "github-actions[bot]"}},
                {"user": {"type": "User", "login": "user1"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"],
            json=[{"user": {"type": "Bot", "login": "dependabot[bot]"}}],
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = (
            gh_pr_metrics.count_comments(pr, "owner", "repo", None, default_config)
        )
        assert total == 3
        assert non_ai_bot == 2
        assert ai_bot == 0
        assert non_ai_bot_names == "dependabot[bot],github-actions[bot]"
        assert ai_bot_names == ""

    def test_count_comments_with_ai_bot_comments(self, requests_mock, default_config):
        """Test counting AI bot comments separately."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "Bot", "login": "cursor[bot]"}},
                {"user": {"type": "Bot", "login": "github-actions[bot]"}},
                {"user": {"type": "User", "login": "user1"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"],
            json=[{"user": {"type": "Bot", "login": "cursor[bot]"}}],
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        # Test with default CLI pattern
        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = (
            gh_pr_metrics.count_comments(pr, "owner", "repo", None, default_config)
        )
        assert total == 4
        assert non_ai_bot == 1
        assert ai_bot == 2
        assert non_ai_bot_names == "github-actions[bot]"
        assert ai_bot_names == "cursor[bot]"

    def test_count_comments_with_none_ai_bot_pattern(
        self, requests_mock, default_config
    ):
        """Test that empty ai_bots config treats all bots as non-AI bots."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "Bot", "login": "cursor[bot]"}},
                {"user": {"type": "Bot", "login": "github-actions[bot]"}},
                {"user": {"type": "User", "login": "user1"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"],
            json=[{"user": {"type": "Bot", "login": "cursor[bot]"}}],
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        # Create config with no AI bots defined
        empty_config = gh_pr_metrics.Config(
            {"ai_bots": {"always": [], "conditional": []}}
        )

        # Test with empty config - all bots should be non-AI
        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = (
            gh_pr_metrics.count_comments(pr, "owner", "repo", None, empty_config)
        )
        assert total == 4
        assert non_ai_bot == 3  # All bots are non-AI when no patterns configured
        assert ai_bot == 0
        assert non_ai_bot_names == "cursor[bot],github-actions[bot]"
        assert ai_bot_names == ""

    def test_count_comments_with_ai_review_body(self, requests_mock, default_config):
        """Test that AI code review in review body is detected."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # No issue or review comments
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])

        # Reviews with bodies - one AI, one human
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews",
            json=[
                {
                    "user": {"type": "Bot", "login": "github-actions[bot]"},
                    "state": "COMMENTED",
                    "body": (
                        "## 📋 Code Review Summary\n\n"
                        "This PR looks good.\n\nFiles Reviewed: 5 files"
                    ),
                },
                {
                    "user": {"type": "User", "login": "human-reviewer"},
                    "state": "APPROVED",
                    "body": "LGTM",
                },
            ],
        )

        # Create config with conditional detection for github-actions[bot]
        ai_review_config = gh_pr_metrics.Config(
            {
                "ai_bots": {
                    "conditional": [
                        {
                            "name": "github-actions\\[bot\\]",
                            "content_patterns": [
                                "Code Review Summary",
                                "Files Reviewed",
                            ],
                            "match_any": True,
                        }
                    ]
                }
            }
        )

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = (
            gh_pr_metrics.count_comments(pr, "owner", "repo", None, ai_review_config)
        )

        # Should count the AI review body as 1 AI bot comment
        assert total == 1  # Only bot reviews with body text count
        assert non_ai_bot == 0
        assert ai_bot == 1
        assert ai_bot_names == "github-actions[bot]"


class TestReviewMetrics:
    """Test review metrics calculation."""

    def test_get_review_metrics_no_reviews(self, requests_mock, default_config):
        """Test when there are no reviews."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(reviews_url, json=[])

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(
            pr, "owner", "repo", None
        )
        assert changes == 0
        assert unique == 0
        assert approvals == 0

    def test_get_review_metrics_with_changes_requested(
        self, requests_mock, default_config
    ):
        """Test counting change requests."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer2"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(
            pr, "owner", "repo", None
        )
        assert changes == 3  # Total count
        assert unique == 2  # Unique reviewers
        assert approvals == 0

    def test_get_review_metrics_with_approvals(self, requests_mock, default_config):
        """Test counting approvals."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "APPROVED"},
                {"user": {"login": "reviewer2"}, "state": "APPROVED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(
            pr, "owner", "repo", None
        )
        assert changes == 0
        assert unique == 0
        assert approvals == 2

    def test_get_review_metrics_reviewer_changes_state(
        self, requests_mock, default_config
    ):
        """Test when reviewer changes their review state."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer1"}, "state": "APPROVED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(
            pr, "owner", "repo", None
        )
        assert changes == 1  # Total change requests
        assert unique == 1  # Unique reviewer who requested changes
        assert approvals == 1  # Most recent state is approved


class TestDerivedTimeMetrics:
    """Test derived time metrics (days_open, days_in_review)."""

    def test_days_open_for_merged_pr(self, requests_mock, default_config):
        """Test days_open calculation for merged PR."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": "2024-01-11T00:00:00Z",  # 10 days later
            "closed_at": "2024-01-11T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API calls
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events", json=[]
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        assert result["days_open"] == 10.0
        assert result["days_in_review"] == 10.0  # Never draft, so same as days_open

    def test_days_in_review_excludes_draft_time(self, requests_mock, default_config):
        """Test that days_in_review excludes draft period."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": "2024-01-11T00:00:00Z",
            "closed_at": "2024-01-11T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock ready_for_review event (marked ready 3 days after creation)
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events",
            json=[{"event": "ready_for_review", "created_at": "2024-01-04T00:00:00Z"}],
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        assert result["days_open"] == 10.0  # Jan 1 → Jan 11
        assert result["days_in_review"] == 7.0  # Jan 4 (ready) → Jan 11

    def test_days_open_for_open_pr(self, requests_mock, default_config):
        """Test days_open calculation uses current time for open PRs."""
        from datetime import datetime, timezone

        # PR created 5 days ago
        now = datetime.now(timezone.utc)
        from datetime import timedelta

        created = now - timedelta(days=5)

        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": created.isoformat(),
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API calls
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events", json=[]
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        # Should be approximately 5 days (allow small variance for test execution time)
        assert 4.99 <= result["days_open"] <= 5.01
        assert 4.99 <= result["days_in_review"] <= 5.01

    def test_days_metrics_handle_errors_gracefully(self, requests_mock, default_config):
        """Test that time metrics handle missing/invalid timestamps gracefully."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": "invalid-date",  # Invalid timestamp
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API calls
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events", json=[]
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        # Should have empty strings for time metrics
        assert result["days_open"] == ""
        assert result["days_in_review"] == ""
        assert "time_metrics" in result["errors"]


class TestComplexityMetrics:
    """Test PR complexity metrics extraction."""

    def test_complexity_metrics_extracted(self, requests_mock, default_config):
        """Test that complexity metrics are extracted from PR object."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
            "additions": 150,
            "deletions": 50,
            "changed_files": 10,
        }

        # Mock API calls
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events", json=[]
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        assert result["lines_added"] == 150
        assert result["lines_deleted"] == 50
        assert result["files_changed"] == 10
        assert result["total_line_changes"] == 200

    def test_complexity_metrics_defaults_to_zero(self, requests_mock, default_config):
        """Test that missing complexity metrics default to 0."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
            # No additions, deletions, or changed_files
        }

        # Mock API calls
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events", json=[]
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        assert result["lines_added"] == 0
        assert result["lines_deleted"] == 0
        assert result["files_changed"] == 0
        assert result["total_line_changes"] == 0

    def test_total_line_changes_calculation(self, requests_mock, default_config):
        """Test that total_line_changes is correctly calculated."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
            "additions": 500,
            "deletions": 300,
            "changed_files": 25,
        }

        # Mock API calls
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events", json=[]
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[]
        )

        result = gh_pr_metrics.process_pr(pr, {}, "owner", "repo", None, default_config)

        assert result["total_line_changes"] == 800  # 500 + 300


class TestRecalculateBotFields:
    """Test MetricsGenerator.recalculate_bot_fields for reprocessing."""

    def test_ai_bot_reclassification(self, default_config):
        """Test that AI bot classification uses current config."""
        pr_json = {
            "pr_number": 42,
            "issue_comments": [
                {"user": "cursor[bot]", "user_type": "Bot", "body": "AI review"},
                {"user": "dependabot[bot]", "user_type": "Bot", "body": "Bump"},
            ],
            "review_comments": [
                {"user": "Copilot", "user_type": "Bot", "body": "Suggestion"},
            ],
            "reviews": [],
        }
        gen = gh_pr_metrics.MetricsGenerator(default_config, gh_pr_metrics.logger)
        result = gen.recalculate_bot_fields(pr_json)

        assert result["total_comment_count"] == 3
        assert result["ai_bot_comment_count"] == 2
        assert result["non_ai_bot_comment_count"] == 1
        assert "cursor[bot]" in result["ai_bot_login_names"]
        assert "Copilot" in result["ai_bot_login_names"]
        assert "dependabot[bot]" in result["non_ai_bot_login_names"]

    def test_only_returns_bot_fields(self, default_config):
        """Test that only bot classification fields are returned."""
        pr_json = {
            "pr_number": 1,
            "issue_comments": [],
            "review_comments": [],
            "reviews": [],
        }
        gen = gh_pr_metrics.MetricsGenerator(default_config, gh_pr_metrics.logger)
        result = gen.recalculate_bot_fields(pr_json)

        expected_keys = {
            "total_comment_count",
            "non_ai_bot_comment_count",
            "ai_bot_comment_count",
            "non_ai_bot_login_names",
            "ai_bot_login_names",
        }
        assert set(result.keys()) == expected_keys

    def test_config_change_reclassifies(self):
        """Test that changing config changes classification."""
        pr_json = {
            "pr_number": 1,
            "issue_comments": [
                {"user": "coderabbitai", "user_type": "Bot", "body": "Review"},
            ],
            "review_comments": [],
            "reviews": [],
        }

        # Without coderabbitai in config
        config_without = gh_pr_metrics.Config({"ai_bots": {"always": []}})
        gen = gh_pr_metrics.MetricsGenerator(config_without, gh_pr_metrics.logger)
        result = gen.recalculate_bot_fields(pr_json)
        assert result["ai_bot_comment_count"] == 0
        assert result["non_ai_bot_comment_count"] == 1

        # With coderabbitai in config
        config_with = gh_pr_metrics.Config({"ai_bots": {"always": ["coderabbitai"]}})
        gen = gh_pr_metrics.MetricsGenerator(config_with, gh_pr_metrics.logger)
        result = gen.recalculate_bot_fields(pr_json)
        assert result["ai_bot_comment_count"] == 1
        assert result["non_ai_bot_comment_count"] == 0


class TestReprocessRepository:
    """Test reprocess_repository function."""

    def _write_csv(self, csv_file, rows):
        """Write CSV rows for test setup."""
        import csv as csv_mod

        fieldnames = gh_pr_metrics.CSVManager().get_fieldnames()
        with open(csv_file, "w", newline="", encoding="utf-8") as f:
            writer = csv_mod.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(rows)

    def _make_csv_row(self, pr_number, **overrides):
        """Build a minimal CSV row dict."""
        row = {
            "pr_number": pr_number,
            "title": f"PR {pr_number}",
            "author": "testuser",
            "created_at": "2024-01-01T00:00:00Z",
            "ready_for_review_at": "2024-01-01T12:00:00Z",
            "merged_at": "2024-01-02T00:00:00Z",
            "closed_at": "2024-01-02T00:00:00Z",
            "days_open": "1.0",
            "days_in_review": "0.5",
            "total_comment_count": "1",
            "non_ai_bot_comment_count": "1",
            "ai_bot_comment_count": "0",
            "non_ai_bot_login_names": "coderabbitai",
            "ai_bot_login_names": "",
            "changes_requested_count": "0",
            "unique_change_requesters": "0",
            "approval_count": "1",
            "status": "merged",
            "url": f"https://github.com/owner/repo/pull/{pr_number}",
            "errors": "",
            "lines_added": "10",
            "lines_deleted": "5",
            "files_changed": "2",
            "total_line_changes": "15",
        }
        row.update(overrides)
        return row

    def test_preserves_non_bot_fields(self, tmp_path, default_config):
        """Test that reprocessing preserves fields not related to bots."""
        raw_dir = tmp_path / "raw" / "github.com" / "owner" / "repo"
        raw_dir.mkdir(parents=True)
        default_config.raw_data_dir = str(tmp_path / "raw")

        # Write cached JSON with no bot comments
        pr_json = {
            "pr_number": 1,
            "issue_comments": [],
            "review_comments": [],
            "reviews": [],
        }
        with open(raw_dir / "1.json", "w") as f:
            json.dump(pr_json, f)

        # Write existing CSV with specific values we want preserved
        csv_file = str(tmp_path / "output.csv")
        self._write_csv(
            csv_file,
            [
                self._make_csv_row(
                    1,
                    ready_for_review_at="2024-01-01T12:00:00Z",
                    days_in_review="0.5",
                    days_open="1.0",
                    approval_count="2",
                )
            ],
        )

        result = gh_pr_metrics.reprocess_repository(
            "owner", "repo", csv_file, default_config, workers=1
        )
        assert result == gh_pr_metrics.EXIT_SUCCESS

        import csv as csv_mod

        with open(csv_file) as f:
            rows = list(csv_mod.DictReader(f))
        assert len(rows) == 1
        # These fields should be preserved from original CSV
        assert rows[0]["ready_for_review_at"] == "2024-01-01T12:00:00Z"
        assert rows[0]["days_in_review"] == "0.5"
        assert rows[0]["days_open"] == "1.0"
        assert rows[0]["approval_count"] == "2"

    def test_updates_bot_fields(self, tmp_path):
        """Test that reprocessing updates bot classification fields."""
        raw_dir = tmp_path / "raw" / "github.com" / "owner" / "repo"
        raw_dir.mkdir(parents=True)

        # Cached JSON has coderabbitai comment
        pr_json = {
            "pr_number": 1,
            "issue_comments": [
                {
                    "user": "coderabbitai",
                    "user_type": "Bot",
                    "body": "Code review",
                },
            ],
            "review_comments": [],
            "reviews": [],
        }
        with open(raw_dir / "1.json", "w") as f:
            json.dump(pr_json, f)

        # Existing CSV has coderabbitai classified as non-AI
        csv_file = str(tmp_path / "output.csv")
        self._write_csv(
            csv_file,
            [
                self._make_csv_row(
                    1,
                    non_ai_bot_comment_count="1",
                    ai_bot_comment_count="0",
                    non_ai_bot_login_names="coderabbitai",
                    ai_bot_login_names="",
                )
            ],
        )

        # Reprocess with coderabbitai now classified as AI
        config = gh_pr_metrics.Config(
            {
                "ai_bots": {"always": ["coderabbitai"]},
                "raw_data_dir": str(tmp_path / "raw"),
            }
        )

        result = gh_pr_metrics.reprocess_repository(
            "owner", "repo", csv_file, config, workers=1
        )
        assert result == gh_pr_metrics.EXIT_SUCCESS

        import csv as csv_mod

        with open(csv_file) as f:
            rows = list(csv_mod.DictReader(f))
        assert len(rows) == 1
        assert rows[0]["ai_bot_comment_count"] == "1"
        assert rows[0]["ai_bot_login_names"] == "coderabbitai"
        assert rows[0]["non_ai_bot_comment_count"] == "0"
        assert rows[0]["non_ai_bot_login_names"] == ""

    def test_no_csv_file(self, tmp_path, default_config):
        """Test reprocess with no existing CSV."""
        default_config.raw_data_dir = str(tmp_path / "raw")
        csv_file = str(tmp_path / "nonexistent.csv")

        result = gh_pr_metrics.reprocess_repository(
            "owner", "repo", csv_file, default_config, workers=1
        )

        assert result == gh_pr_metrics.EXIT_SUCCESS

    def test_no_cache_dir(self, tmp_path, default_config):
        """Test reprocess with no cached JSON directory."""
        default_config.raw_data_dir = str(tmp_path / "nonexistent")

        csv_file = str(tmp_path / "output.csv")
        self._write_csv(csv_file, [self._make_csv_row(1)])

        result = gh_pr_metrics.reprocess_repository(
            "owner", "repo", csv_file, default_config, workers=1
        )

        assert result == gh_pr_metrics.EXIT_SUCCESS

    def test_skips_prs_without_cache(self, tmp_path, default_config):
        """Test that PRs without cached JSON are left unchanged."""
        raw_dir = tmp_path / "raw" / "github.com" / "owner" / "repo"
        raw_dir.mkdir(parents=True)
        default_config.raw_data_dir = str(tmp_path / "raw")

        # Only cache PR #1, not PR #2
        pr_json = {
            "pr_number": 1,
            "issue_comments": [],
            "review_comments": [],
            "reviews": [],
        }
        with open(raw_dir / "1.json", "w") as f:
            json.dump(pr_json, f)

        csv_file = str(tmp_path / "output.csv")
        self._write_csv(
            csv_file,
            [
                self._make_csv_row(1, non_ai_bot_login_names="old_bot"),
                self._make_csv_row(2, non_ai_bot_login_names="preserved"),
            ],
        )

        result = gh_pr_metrics.reprocess_repository(
            "owner", "repo", csv_file, default_config, workers=1
        )
        assert result == gh_pr_metrics.EXIT_SUCCESS

        import csv as csv_mod

        with open(csv_file) as f:
            rows = list(csv_mod.DictReader(f))
        assert len(rows) == 2
        # PR #2 should be unchanged
        pr2 = next(r for r in rows if r["pr_number"] == "2")
        assert pr2["non_ai_bot_login_names"] == "preserved"
