# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for state file management."""

from datetime import datetime, timezone
from unittest import mock

import gh_pr_metrics


class TestStateManagement:
    """Test state file management for differential updates."""

    def test_load_state_file_nonexistent(self, tmp_path):
        """Test loading state file that doesn't exist returns empty dict."""
        state_file = tmp_path / "nonexistent.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            state = gh_pr_metrics.load_state_file()
            assert state == {}

    def test_load_state_file_existing(self, tmp_path):
        """Test loading existing state file."""
        state_file = tmp_path / "state.yaml"
        state_file.write_text(
            "https://github.com/owner/repo:\n  csv_file: metrics.csv\n"
            "  timestamp: '2024-01-01T00:00:00'\n"
        )

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            state = gh_pr_metrics.load_state_file()
            assert "https://github.com/owner/repo" in state
            assert state["https://github.com/owner/repo"]["timestamp"] == "2024-01-01T00:00:00"
            assert state["https://github.com/owner/repo"]["csv_file"] == "metrics.csv"

    def test_save_state_file(self, tmp_path):
        """Test saving state file."""
        state_file = tmp_path / "state.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            state = {
                "https://github.com/owner/repo": {
                    "timestamp": "2024-01-01T00:00:00",
                    "csv_file": "metrics.csv",
                }
            }
            gh_pr_metrics.save_state_file(state)

            assert state_file.exists()
            content = state_file.read_text()
            assert "https://github.com/owner/repo" in content
            assert "2024-01-01T00:00:00" in content
            assert "metrics.csv" in content

    def test_get_last_update_date_exists(self, tmp_path):
        """Test getting last update date when it exists."""
        state_file = tmp_path / "state.yaml"
        state_file.write_text(
            "https://github.com/owner/repo:\n  csv_file: metrics.csv\n"
            "  timestamp: '2024-01-01T00:00:00'\n"
        )

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            last_update = gh_pr_metrics.get_last_update_date("owner", "repo")
            assert last_update is not None
            assert last_update.year == 2024
            assert last_update.month == 1
            assert last_update.day == 1

    def test_get_last_update_date_not_exists(self, tmp_path):
        """Test getting last update date when it doesn't exist."""
        state_file = tmp_path / "state.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            last_update = gh_pr_metrics.get_last_update_date("owner", "repo")
            assert last_update is None

    def test_update_state_file(self, tmp_path):
        """Test updating state file with new timestamp."""
        state_file = tmp_path / "state.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            timestamp = datetime(2024, 1, 15, 12, 0, 0, tzinfo=timezone.utc)
            gh_pr_metrics.update_state_file("owner", "repo", timestamp, "metrics.csv")

            # Verify state was saved (without timezone component)
            state = gh_pr_metrics.load_state_file()
            repo_key = "https://github.com/owner/repo"
            assert repo_key in state
            assert "2024-01-15T12:00:00" == state[repo_key]["timestamp"]
            assert "metrics.csv" == state[repo_key]["csv_file"]

    def test_update_state_file_multiple_repos(self, tmp_path):
        """Test state file can track multiple repositories."""
        state_file = tmp_path / "state.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            # Add first repo
            timestamp1 = datetime(2024, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
            gh_pr_metrics.update_state_file("owner1", "repo1", timestamp1, "repo1.csv")

            # Add second repo
            timestamp2 = datetime(2024, 1, 2, 0, 0, 0, tzinfo=timezone.utc)
            gh_pr_metrics.update_state_file("owner2", "repo2", timestamp2, "repo2.csv")

            # Verify both are in state
            state = gh_pr_metrics.load_state_file()
            assert "https://github.com/owner1/repo1" in state
            assert "https://github.com/owner2/repo2" in state
            assert state["https://github.com/owner1/repo1"]["csv_file"] == "repo1.csv"
            assert state["https://github.com/owner2/repo2"]["csv_file"] == "repo2.csv"

    def test_update_state_file_overwrites_existing(self, tmp_path):
        """Test updating state file overwrites previous timestamp."""
        state_file = tmp_path / "state.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            # First update
            timestamp1 = datetime(2024, 1, 1, 0, 0, 0, tzinfo=timezone.utc)
            gh_pr_metrics.update_state_file("owner", "repo", timestamp1, "old.csv")

            # Second update (overwrites)
            timestamp2 = datetime(2024, 1, 15, 0, 0, 0, tzinfo=timezone.utc)
            gh_pr_metrics.update_state_file("owner", "repo", timestamp2, "new.csv")

            # Verify only latest timestamp and file are stored
            state = gh_pr_metrics.load_state_file()
            repo_key = "https://github.com/owner/repo"
            assert repo_key in state
            assert "2024-01-15T00:00:00" == state[repo_key]["timestamp"]
            assert "new.csv" == state[repo_key]["csv_file"]

    def test_get_all_tracked_repos_empty(self, tmp_path):
        """Test getting tracked repos when state file is empty."""
        state_file = tmp_path / "state.yaml"

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            repos = gh_pr_metrics.get_all_tracked_repos()
            assert repos == []

    def test_get_all_tracked_repos_single_repo(self, tmp_path):
        """Test getting tracked repos with single repository."""
        state_file = tmp_path / "state.yaml"
        state_file.write_text(
            "https://github.com/owner/repo:\n  csv_file: metrics.csv\n"
            "  timestamp: '2024-01-01T00:00:00Z'\n"
        )

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            repos = gh_pr_metrics.get_all_tracked_repos()
            assert len(repos) == 1
            assert repos[0]["owner"] == "owner"
            assert repos[0]["repo"] == "repo"
            assert repos[0]["url"] == "https://github.com/owner/repo"
            assert repos[0]["csv_file"] == "metrics.csv"
            assert repos[0]["timestamp"].year == 2024

    def test_get_all_tracked_repos_multiple_repos(self, tmp_path):
        """Test getting tracked repos with multiple repositories."""
        state_file = tmp_path / "state.yaml"
        state_file.write_text(
            "https://github.com/owner1/repo1:\n  csv_file: repo1.csv\n"
            "  timestamp: '2024-01-01T00:00:00Z'\n"
            "https://github.com/owner2/repo2:\n  csv_file: repo2.csv\n"
            "  timestamp: '2024-01-02T00:00:00Z'\n"
        )

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            repos = gh_pr_metrics.get_all_tracked_repos()
            assert len(repos) == 2
            owners = [r["owner"] for r in repos]
            assert "owner1" in owners
            assert "owner2" in owners

    def test_get_all_tracked_repos_invalid_format(self, tmp_path):
        """Test getting tracked repos with invalid state format."""
        state_file = tmp_path / "state.yaml"
        state_file.write_text(
            "https://github.com/owner/repo: invalid_string\n"
            "https://github.com/owner2/repo2:\n  csv_file: repo2.csv\n"
            "  timestamp: '2024-01-02T00:00:00Z'\n"
        )

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            repos = gh_pr_metrics.get_all_tracked_repos()
            # Should only get the valid repo
            assert len(repos) == 1
            assert repos[0]["owner"] == "owner2"

    def test_get_all_tracked_repos_malformed_url(self, tmp_path):
        """Test getting tracked repos with malformed URLs."""
        state_file = tmp_path / "state.yaml"
        state_file.write_text(
            "badurl:\n  csv_file: metrics.csv\n"
            "  timestamp: '2024-01-01T00:00:00Z'\n"
            "https://github.com/owner/repo:\n  csv_file: good.csv\n"
            "  timestamp: '2024-01-02T00:00:00Z'\n"
        )

        with mock.patch.object(gh_pr_metrics, "STATE_FILE", state_file):
            repos = gh_pr_metrics.get_all_tracked_repos()
            # Should only get the valid repo
            assert len(repos) == 1
            assert repos[0]["owner"] == "owner"
