# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for configuration management."""

import pytest

import gh_pr_metrics


class TestConfigLoading:
    """Test configuration file loading and validation."""

    def test_load_config_file_not_found(self):
        """Test that load_config returns default Config for missing file."""
        config = gh_pr_metrics.load_config("/nonexistent/config.yaml")

        # Should return Config with defaults
        assert config.workers == 4
        assert config.log_file == "gh-pr-metrics.log"
        assert config.always_ai_bots == []

    def test_load_config_empty_file(self, tmp_path):
        """Test that load_config returns default Config for empty file."""
        config_file = tmp_path / "empty.yaml"
        config_file.write_text("")

        config = gh_pr_metrics.load_config(str(config_file))

        # Should return Config with defaults
        assert config.workers == 4
        assert config.log_file == "gh-pr-metrics.log"
        assert config.always_ai_bots == []

    def test_load_config_invalid_yaml(self, tmp_path):
        """Test that load_config handles invalid YAML."""
        config_file = tmp_path / "invalid.yaml"
        config_file.write_text("invalid: yaml: syntax: error:")

        with pytest.raises(ValueError, match="Invalid YAML"):
            gh_pr_metrics.load_config(str(config_file))

    def test_load_config_output_pattern_without_placeholders(self, tmp_path):
        """Test that load_config validates output_pattern has placeholders."""
        config_file = tmp_path / "bad_pattern.yaml"
        config_file.write_text("""
output_pattern: "static_file.csv"
""")

        with pytest.raises(ValueError, match="Invalid output_pattern.*must contain"):
            gh_pr_metrics.load_config(str(config_file))

    def test_load_config_output_pattern_with_owner_placeholder(self, tmp_path):
        """Test that output_pattern with {owner} is valid."""
        config_file = tmp_path / "valid_owner.yaml"
        config_file.write_text("""
output_pattern: "data/{owner}_repos.csv"
""")

        config = gh_pr_metrics.load_config(str(config_file))
        assert config.output_pattern == "data/{owner}_repos.csv"

    def test_load_config_output_pattern_with_repo_placeholder(self, tmp_path):
        """Test that output_pattern with {repo} is valid."""
        config_file = tmp_path / "valid_repo.yaml"
        config_file.write_text("""
output_pattern: "data/{repo}.csv"
""")

        config = gh_pr_metrics.load_config(str(config_file))
        assert config.output_pattern == "data/{repo}.csv"

    def test_load_config_valid(self, tmp_path):
        """Test loading a valid configuration file."""
        config_file = tmp_path / "valid.yaml"
        config_file.write_text("""
ai_bots:
  always:
    - "cursor\\\\[bot\\\\]"
  conditional:
    - name: "github-actions\\\\[bot\\\\]"
      content_patterns: ["Code Review"]
      match_any: true
workers: 8
log_file: "test.log"
raw_data_dir: "data/json"
""")

        config = gh_pr_metrics.load_config(str(config_file))

        assert config.workers == 8
        assert config.log_file == "test.log"
        assert config.raw_data_dir == "data/json"
        assert len(config.always_ai_bots) == 1
        assert len(config.conditional_bots) == 1


class TestConfigDefaults:
    """Test Config class defaults."""

    def test_config_with_minimal_dict(self):
        """Test Config with minimal configuration."""
        config = gh_pr_metrics.Config({})

        # Should use defaults
        assert config.workers == 4
        assert config.log_file == "gh-pr-metrics.log"
        assert config.raw_data_dir  # Verify raw_data_dir is set (value may be test-isolated)
        assert config.always_ai_bots == []
        assert config.conditional_bots == []

    def test_config_with_partial_dict(self):
        """Test Config with partial configuration."""
        config = gh_pr_metrics.Config({"workers": 2, "ai_bots": {"always": ["test-bot"]}})

        assert config.workers == 2
        assert config.always_ai_bots == ["test-bot"]
        # Other fields use defaults
        assert config.log_file == "gh-pr-metrics.log"


class TestAIBotDetection:
    """Test AI bot detection logic."""

    def test_always_ai_bot_detection(self):
        """Test detection of always-AI bots using regex."""
        config = gh_pr_metrics.Config(
            {"ai_bots": {"always": ["cursor\\[bot\\]", "claude\\[bot\\]"]}}
        )

        assert config.is_ai_bot("cursor[bot]", "") is True
        assert config.is_ai_bot("claude[bot]", "") is True
        assert config.is_ai_bot("github-actions[bot]", "") is False
        assert config.is_ai_bot("regular-user", "") is False

    def test_conditional_ai_bot_with_matching_content(self):
        """Test conditional bot detection with matching content."""
        config = gh_pr_metrics.Config(
            {
                "ai_bots": {
                    "conditional": [
                        {
                            "name": "github-actions\\[bot\\]",
                            "content_patterns": ["Code Review Summary", "Files Reviewed"],
                            "match_any": True,
                        }
                    ]
                }
            }
        )

        # Matches pattern
        assert (
            config.is_ai_bot("github-actions[bot]", "📋 Code Review Summary\nSome details") is True
        )
        assert config.is_ai_bot("github-actions[bot]", "Files Reviewed: 5") is True

        # No match - different content
        assert config.is_ai_bot("github-actions[bot]", "Deployed to staging") is False

        # No match - different bot name
        assert config.is_ai_bot("other-bot", "Code Review Summary") is False

    def test_conditional_ai_bot_match_all_patterns(self):
        """Test conditional bot with match_any=False (all patterns required)."""
        config = gh_pr_metrics.Config(
            {
                "ai_bots": {
                    "conditional": [
                        {
                            "name": "github-actions\\[bot\\]",
                            "content_patterns": ["Code Review Summary", "Files Reviewed"],
                            "match_any": False,
                        }
                    ]
                }
            }
        )

        # Both patterns present
        assert (
            config.is_ai_bot("github-actions[bot]", "Code Review Summary\nFiles Reviewed: 5")
            is True
        )

        # Only one pattern
        assert config.is_ai_bot("github-actions[bot]", "Code Review Summary") is False
        assert config.is_ai_bot("github-actions[bot]", "Files Reviewed: 3") is False

    def test_combined_always_and_conditional(self):
        """Test config with both always and conditional bots."""
        config = gh_pr_metrics.Config(
            {
                "ai_bots": {
                    "always": ["cursor\\[bot\\]"],
                    "conditional": [
                        {
                            "name": "github-actions\\[bot\\]",
                            "content_patterns": ["Code Review"],
                            "match_any": True,
                        }
                    ],
                }
            }
        )

        # Always bot - no content needed
        assert config.is_ai_bot("cursor[bot]", "") is True
        assert config.is_ai_bot("cursor[bot]", "anything") is True

        # Conditional bot - needs content
        assert config.is_ai_bot("github-actions[bot]", "Code Review done") is True
        assert config.is_ai_bot("github-actions[bot]", "No match") is False

    def test_conditional_bot_empty_comment_body(self):
        """Test that conditional bots return False for empty comment."""
        config = gh_pr_metrics.Config(
            {
                "ai_bots": {
                    "conditional": [
                        {
                            "name": "github-actions\\[bot\\]",
                            "content_patterns": ["Code Review"],
                            "match_any": True,
                        }
                    ]
                }
            }
        )

        assert config.is_ai_bot("github-actions[bot]", "") is False
        assert config.is_ai_bot("github-actions[bot]", None) is False


class TestConditionalBotConfig:
    """Test ConditionalBotConfig class."""

    def test_matches_content_with_match_any(self):
        """Test content matching with match_any=True."""
        bot_config = gh_pr_metrics.ConditionalBotConfig(
            name="test-bot", content_patterns=["pattern1", "pattern2"], match_any=True
        )

        assert bot_config.matches_content("This has pattern1 in it") is True
        assert bot_config.matches_content("This has pattern2 in it") is True
        assert bot_config.matches_content("This has both pattern1 and pattern2") is True
        assert bot_config.matches_content("This has neither") is False

    def test_matches_content_with_match_all(self):
        """Test content matching with match_any=False."""
        bot_config = gh_pr_metrics.ConditionalBotConfig(
            name="test-bot", content_patterns=["pattern1", "pattern2"], match_any=False
        )

        assert bot_config.matches_content("This has both pattern1 and pattern2") is True
        assert bot_config.matches_content("Only pattern1 here") is False
        assert bot_config.matches_content("Only pattern2 here") is False
        assert bot_config.matches_content("Neither pattern") is False

    def test_matches_content_empty_body(self):
        """Test that empty content never matches."""
        bot_config = gh_pr_metrics.ConditionalBotConfig(
            name="test-bot", content_patterns=["pattern1"], match_any=True
        )

        assert bot_config.matches_content("") is False
        assert bot_config.matches_content(None) is False
