# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for pull request processing logic."""

import gh_pr_metrics


class TestPRStatusDetermination:
    """Test PR status determination logic."""

    def test_determine_draft_status(self):
        """Test identifying draft PRs."""
        pr = {"draft": True, "state": "open", "merged_at": None}
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "draft"

    def test_determine_merged_status(self, requests_mock):
        """Test identifying merged PRs and extracting merge timestamp."""
        pr = {
            "number": 1,
            "title": "Merged PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "merged_at": "2024-01-05T12:00:00Z",
            "closed_at": "2024-01-05T12:00:00Z",
            "created_at": "2024-01-01T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Test status determination
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "merged"

        # Test full PR processing extracts timestamps
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(reviews_url, json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)
        assert result["merged_at"] == "2024-01-05T12:00:00Z"
        assert result["closed_at"] == "2024-01-05T12:00:00Z"
        assert result["status"] == "merged"

    def test_determine_closed_status(self, requests_mock):
        """Test identifying closed (not merged) PRs and extracting close timestamp."""
        pr = {
            "number": 2,
            "title": "Closed PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "merged_at": None,
            "closed_at": "2024-01-10T15:30:00Z",
            "created_at": "2024-01-08T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/2",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/2/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/2/comments",
        }

        # Test status determination
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "closed"

        # Test full PR processing extracts timestamps
        events_url = "https://api.github.com/repos/owner/repo/issues/2/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/2/reviews"
        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(reviews_url, json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)
        assert result["merged_at"] == ""  # Not merged
        assert result["closed_at"] == "2024-01-10T15:30:00Z"
        assert result["status"] == "closed"

    def test_determine_open_status(self):
        """Test identifying open PRs."""
        pr = {"draft": False, "state": "open", "merged_at": None}
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "open"


class TestReadyForReviewTime:
    """Test ready for review timestamp determination."""

    def test_ready_for_review_never_draft(self, requests_mock):
        """Test PR that was never a draft."""
        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return no ready_for_review events
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(events_url, json=[])

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-01T00:00:00Z"

    def test_ready_for_review_with_event(self, requests_mock):
        """Test PR that was converted from draft."""
        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return ready_for_review event
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(
            events_url,
            json=[{"event": "ready_for_review", "created_at": "2024-01-02T00:00:00Z"}],
        )

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-02T00:00:00Z"

    def test_ready_for_review_api_error(self, requests_mock):
        """Test handling API errors when fetching events."""
        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return error
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(events_url, status_code=500)

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        # Should fall back to created_at
        assert result == "2024-01-01T00:00:00Z"


class TestCommentCounting:
    """Test comment counting logic."""

    def test_count_comments_no_comments(self, requests_mock):
        """Test counting when there are no comments."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])

        total, bot = gh_pr_metrics.count_comments(pr, "owner", "repo", None)
        assert total == 0
        assert bot == 0

    def test_count_comments_with_regular_comments(self, requests_mock):
        """Test counting regular comments."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[{"user": {"type": "User"}}, {"user": {"type": "User"}}],
        )
        requests_mock.get(pr["review_comments_url"], json=[{"user": {"type": "User"}}])

        total, bot = gh_pr_metrics.count_comments(pr, "owner", "repo", None)
        assert total == 3
        assert bot == 0

    def test_count_comments_with_bot_comments(self, requests_mock):
        """Test counting bot comments separately."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[{"user": {"type": "Bot"}}, {"user": {"type": "User"}}],
        )
        requests_mock.get(pr["review_comments_url"], json=[{"user": {"type": "Bot"}}])

        total, bot = gh_pr_metrics.count_comments(pr, "owner", "repo", None)
        assert total == 3
        assert bot == 2


class TestReviewMetrics:
    """Test review metrics calculation."""

    def test_get_review_metrics_no_reviews(self, requests_mock):
        """Test when there are no reviews."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(reviews_url, json=[])

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 0
        assert unique == 0
        assert approvals == 0

    def test_get_review_metrics_with_changes_requested(self, requests_mock):
        """Test counting change requests."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer2"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 3  # Total count
        assert unique == 2  # Unique reviewers
        assert approvals == 0

    def test_get_review_metrics_with_approvals(self, requests_mock):
        """Test counting approvals."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "APPROVED"},
                {"user": {"login": "reviewer2"}, "state": "APPROVED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 0
        assert unique == 0
        assert approvals == 2

    def test_get_review_metrics_reviewer_changes_state(self, requests_mock):
        """Test when reviewer changes their review state."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer1"}, "state": "APPROVED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 1  # Total change requests
        assert unique == 1  # Unique reviewer who requested changes
        assert approvals == 1  # Most recent state is approved
