# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for utility functions."""

from unittest import mock

import gh_pr_metrics


class TestGitHubToken:
    """Test GitHub token retrieval utility."""

    def test_get_github_token_from_env(self):
        """Test getting GitHub token from environment."""
        with mock.patch.dict("os.environ", {"GITHUB_TOKEN": "test_token"}):
            token = gh_pr_metrics.get_github_token()
            assert token == "test_token"

    def test_get_github_token_none_when_not_set(self):
        """Test getting GitHub token when not set."""
        with mock.patch.dict("os.environ", {}, clear=True):
            token = gh_pr_metrics.get_github_token()
            assert token is None
