# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for date and timestamp handling."""

import pytest

import gh_pr_metrics


class TestDateParsing:
    """Test date and timestamp parsing."""

    def test_parse_iso8601_timestamp(self):
        """Test parsing ISO 8601 timestamp."""
        result = gh_pr_metrics.parse_timestamp("2024-01-01T00:00:00Z")
        assert result.year == 2024
        assert result.month == 1
        assert result.day == 1

    def test_parse_unix_timestamp(self):
        """Test parsing Unix timestamp."""
        result = gh_pr_metrics.parse_timestamp("1704067200")  # 2024-01-01 00:00:00 UTC
        # Just verify we can parse it - actual time depends on local timezone
        assert result.month in [1, 12]  # Could be Dec 31 or Jan 1 depending on timezone

    def test_parse_rfc3339_timestamp(self):
        """Test parsing RFC 3339 timestamp."""
        result = gh_pr_metrics.parse_timestamp("2024-06-15T12:30:45+00:00")
        assert result.year == 2024
        assert result.month == 6
        assert result.day == 15

    def test_parse_invalid_timestamp_raises_error(self):
        """Test that invalid timestamp raises an error."""
        with pytest.raises(Exception):
            gh_pr_metrics.parse_timestamp("invalid")
