# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for GitHub API interactions."""

from unittest import mock
import pytest
import requests

import gh_pr_metrics


class TestGitHubAPIClient:
    """Test GitHub API client functionality."""

    def test_get_github_token_from_env(self):
        """Test getting GitHub token from environment."""
        with mock.patch.dict("os.environ", {"GITHUB_TOKEN": "test_token"}):
            token = gh_pr_metrics.get_github_token()
            assert token == "test_token"

    def test_get_github_token_none_when_not_set(self):
        """Test getting GitHub token when not set."""
        with mock.patch.dict("os.environ", {}, clear=True):
            token = gh_pr_metrics.get_github_token()
            assert token is None

    def test_make_github_request_success(self, requests_mock):
        """Test successful GitHub API request."""
        url = "https://api.github.com/repos/owner/repo"
        requests_mock.get(url, json={"name": "repo"})

        result = gh_pr_metrics.make_github_request(url)
        assert result == {"name": "repo"}

    def test_make_github_request_with_token(self, requests_mock):
        """Test GitHub API request with authentication token."""
        url = "https://api.github.com/repos/owner/repo"
        requests_mock.get(url, json={"name": "repo"})

        gh_pr_metrics.make_github_request(url, token="test_token")
        assert "Authorization" in requests_mock.last_request.headers
        assert requests_mock.last_request.headers["Authorization"] == "Bearer test_token"

    def test_make_github_request_rate_limit_error(self, requests_mock):
        """Test handling of rate limit errors."""
        url = "https://api.github.com/repos/owner/repo"
        requests_mock.get(
            url,
            status_code=403,
            json={"message": "rate limit"},
            headers={
                "X-RateLimit-Remaining": "0",
                "X-RateLimit-Limit": "5000",
                "X-RateLimit-Reset": "1699999999",
            },
        )

        with pytest.raises(gh_pr_metrics.GitHubAPIError, match="rate limit"):
            gh_pr_metrics.make_github_request(url)

    def test_make_github_request_not_found_error(self, requests_mock):
        """Test handling of 404 errors."""
        url = "https://api.github.com/repos/owner/repo"
        requests_mock.get(url, status_code=404)

        with pytest.raises(gh_pr_metrics.GitHubAPIError, match="not found"):
            gh_pr_metrics.make_github_request(url)

    def test_make_github_request_network_error(self, requests_mock):
        """Test handling of network errors."""
        url = "https://api.github.com/repos/owner/repo"
        requests_mock.get(url, exc=requests.exceptions.ConnectionError)

        with pytest.raises(gh_pr_metrics.GitHubAPIError, match="Network error"):
            gh_pr_metrics.make_github_request(url)
