# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for date range chunking and rate limit handling."""

from datetime import datetime, timedelta, timezone
import pytest

import gh_pr_metrics


@pytest.fixture(autouse=True)
def reset_quota_manager():
    """Reset quota manager before each test to prevent state pollution."""
    gh_pr_metrics.quota_manager._remaining = 0
    gh_pr_metrics.quota_manager._limit = 0
    gh_pr_metrics.quota_manager._reset = 0
    yield
    # Cleanup after test
    gh_pr_metrics.quota_manager._remaining = 0
    gh_pr_metrics.quota_manager._limit = 0
    gh_pr_metrics.quota_manager._reset = 0


class TestRateLimitHandling:
    """Test rate limit estimation and checking."""

    def test_estimate_api_calls_for_prs(self):
        """Test API call estimation."""
        # 10 PRs should estimate 40 calls (4 per PR)
        estimated = gh_pr_metrics.estimate_api_calls_for_prs(10)
        assert estimated == 40

        # 0 PRs should estimate 0 calls
        estimated = gh_pr_metrics.estimate_api_calls_for_prs(0)
        assert estimated == 0


class TestChunkDeduplication:
    """Test that overlapping chunks don't reprocess the same PRs."""

    def test_duplicate_pr_filtering_in_chunks(self):
        """Test that duplicate PRs are filtered out in overlapping chunks."""
        # Create mock PRs
        pr_100 = {"number": 100, "created_at": "2024-01-30T12:00:00Z"}
        pr_101 = {"number": 101, "created_at": "2024-02-01T12:00:00Z"}

        # Simulate chunk 1 fetched PRs
        chunk1_prs = [pr_100]

        # Simulate chunk 2 fetched PRs (overlap includes pr_100 again)
        chunk2_prs = [pr_100, pr_101]

        # Track processed PRs
        processed_pr_numbers = set()

        # Process chunk 1
        new_prs_chunk1 = [pr for pr in chunk1_prs if pr["number"] not in processed_pr_numbers]
        for pr in new_prs_chunk1:
            processed_pr_numbers.add(pr["number"])

        # Should process 1 PR
        assert len(new_prs_chunk1) == 1
        assert new_prs_chunk1[0]["number"] == 100

        # Process chunk 2
        new_prs_chunk2 = [pr for pr in chunk2_prs if pr["number"] not in processed_pr_numbers]
        for pr in new_prs_chunk2:
            processed_pr_numbers.add(pr["number"])

        # Should only process PR 101 (PR 100 already processed)
        assert len(new_prs_chunk2) == 1
        assert new_prs_chunk2[0]["number"] == 101

        # Total processed should be 2 unique PRs
        assert len(processed_pr_numbers) == 2
        assert processed_pr_numbers == {100, 101}
