# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for main application flow."""

from unittest import mock
import sys

import gh_pr_metrics


class TestMain:
    """Test main application entry point."""

    def test_main_returns_error_without_repo(self):
        """Test that main() returns error when repo cannot be determined."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics"]):
            with mock.patch("gh_pr_metrics.get_repo_from_git", return_value=(None, None)):
                result = gh_pr_metrics.main()
                assert result == 1

    def test_main_with_explicit_repo(self, requests_mock):
        """Test main with explicitly specified repo."""
        # Mock the GitHub API to return empty PRs list
        requests_mock.get(
            "https://api.github.com/repos/testowner/testrepo/pulls",
            json=[],
        )

        with mock.patch.object(
            sys,
            "argv",
            ["gh-pr-metrics", "--owner", "testowner", "--repo", "testrepo"],
        ):
            result = gh_pr_metrics.main()
            assert result == 0
