# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for repository initialization mode."""

from unittest import mock
import sys
import pytest

import gh_pr_metrics


class TestInitMode:
    """Test repository initialization functionality."""

    @pytest.fixture(autouse=True)
    def mock_load_config(self, default_config):
        """Mock load_config for all tests in this class."""
        with mock.patch("gh_pr_metrics.load_config", return_value=default_config):
            yield

    def test_init_requires_owner(self):
        """Test that --init requires --owner."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics", "--init", "--output", "test.csv"]):
            result = gh_pr_metrics.main()
            assert result == 1

    def test_init_requires_output(self):
        """Test that --init requires --output."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics", "--init", "--owner", "testowner"]):
            result = gh_pr_metrics.main()
            assert result == 1

    def test_init_cannot_use_end_date(self):
        """Test that --init cannot be used with --end."""
        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--owner",
                "testowner",
                "--output",
                "test.csv",
                "--end",
                "2024-12-31",
            ],
        ):
            result = gh_pr_metrics.main()
            assert result == 1

    def test_init_cannot_use_update(self):
        """Test that --init cannot be used with --update."""
        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--update",
                "--owner",
                "testowner",
                "--output",
                "test.csv",
            ],
        ):
            result = gh_pr_metrics.main()
            assert result == 1

    def test_init_single_repo(self, requests_mock, tmp_path):
        """Test initializing a single repository."""
        state_file = tmp_path / "state.yaml"
        csv_file = tmp_path / "test.csv"

        # Mock rate limit check at startup
        requests_mock.get(
            "https://api.github.com/rate_limit",
            json={
                "resources": {
                    "core": {
                        "limit": 5000,
                        "remaining": 4999,
                        "reset": 1699999999,
                    }
                }
            },
        )

        # Mock repo validation
        requests_mock.get(
            "https://api.github.com/repos/testowner/testrepo",
            json={"name": "testrepo", "owner": {"login": "testowner"}},
        )

        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--owner",
                "testowner",
                "--repo",
                "testrepo",
                "--output",
                str(csv_file),
                "--start",
                "2024-01-01",
            ],
        ):
            with mock.patch.object(gh_pr_metrics.state_manager, "_state_file", state_file):
                result = gh_pr_metrics.main()
                assert result == 0

                # Verify state file (within mock context)
                state = gh_pr_metrics.state_manager.load()
                assert "https://github.com/testowner/testrepo" in state
                assert state["https://github.com/testowner/testrepo"]["csv_file"] == str(csv_file)

        # CSV file not created until first update with actual data
        assert not csv_file.exists()

    def test_init_all_owner_repos(self, requests_mock, tmp_path):
        """Test initializing all repos for an owner."""
        state_file = tmp_path / "state.yaml"
        output_dir = tmp_path / "data"
        output_pattern = str(output_dir / "{owner}-{repo}.csv")

        # Mock rate limit check at startup
        requests_mock.get(
            "https://api.github.com/rate_limit",
            json={
                "resources": {
                    "core": {
                        "limit": 5000,
                        "remaining": 4999,
                        "reset": 1699999999,
                    }
                }
            },
        )

        # Mock listing repos
        requests_mock.get(
            "https://api.github.com/orgs/testowner/repos",
            json=[
                {"name": "repo1"},
                {"name": "repo2"},
                {"name": "repo3"},
            ],
        )

        # Mock repo validation
        requests_mock.get(
            "https://api.github.com/repos/testowner/repo1",
            json={"name": "repo1", "owner": {"login": "testowner"}},
        )
        requests_mock.get(
            "https://api.github.com/repos/testowner/repo2",
            json={"name": "repo2", "owner": {"login": "testowner"}},
        )
        requests_mock.get(
            "https://api.github.com/repos/testowner/repo3",
            json={"name": "repo3", "owner": {"login": "testowner"}},
        )

        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--owner",
                "testowner",
                "--output",
                output_pattern,
                "--start",
                "2024-01-01",
            ],
        ):
            with mock.patch.object(gh_pr_metrics.state_manager, "_state_file", state_file):
                result = gh_pr_metrics.main()
                assert result == 0

                # Verify state file has all repos (within mock context)
                state = gh_pr_metrics.state_manager.load()
                assert len(state) == 3
                assert "https://github.com/testowner/repo1" in state
                assert "https://github.com/testowner/repo2" in state
                assert "https://github.com/testowner/repo3" in state

        # CSV files not created until first update with actual data
        assert not (output_dir / "testowner-repo1.csv").exists()
        assert not (output_dir / "testowner-repo2.csv").exists()
        assert not (output_dir / "testowner-repo3.csv").exists()

    def test_init_initializes_all_repos_without_validation(self, requests_mock, tmp_path):
        """
        Test that init initializes all repos without validation.
        Access errors will show during processing.
        """
        state_file = tmp_path / "state.yaml"
        output_dir = tmp_path / "data"
        output_pattern = str(output_dir / "{owner}-{repo}.csv")

        # Mock rate limit check at startup
        requests_mock.get(
            "https://api.github.com/rate_limit",
            json={
                "resources": {
                    "core": {
                        "limit": 5000,
                        "remaining": 4999,
                        "reset": 1699999999,
                    }
                }
            },
        )

        # Mock listing repos
        requests_mock.get(
            "https://api.github.com/orgs/testowner/repos",
            json=[
                {"name": "repo1"},
                {"name": "repo2"},
            ],
        )

        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--owner",
                "testowner",
                "--output",
                output_pattern,
            ],
        ):
            with mock.patch.object(gh_pr_metrics.state_manager, "_state_file", state_file):
                result = gh_pr_metrics.main()
                # Should succeed - all repos initialized without validation
                assert result == 0

                # Both repos should be in state (no validation, both initialized)
                state = gh_pr_metrics.state_manager.load()
                assert len(state) == 2
                assert "https://github.com/testowner/repo1" in state
                assert "https://github.com/testowner/repo2" in state

    def test_init_skips_already_tracked_repos(self, requests_mock, tmp_path):
        """Test that init skips repos already in state file."""
        state_file = tmp_path / "state.yaml"
        csv_file = tmp_path / "existing.csv"
        output_dir = tmp_path / "data"
        output_pattern = str(output_dir / "{owner}-{repo}.csv")

        # Create existing state
        csv_file.write_text("pr_number,title\n")
        state_file.write_text(
            f"https://github.com/testowner/existing:\n"
            f"  csv_file: {csv_file}\n"
            f"  timestamp: '2024-01-01T00:00:00'\n"
        )

        # Mock rate limit check at startup
        requests_mock.get(
            "https://api.github.com/rate_limit",
            json={
                "resources": {
                    "core": {
                        "limit": 5000,
                        "remaining": 4999,
                        "reset": 1699999999,
                    }
                }
            },
        )

        # Mock listing repos
        requests_mock.get(
            "https://api.github.com/orgs/testowner/repos",
            json=[
                {"name": "existing"},
                {"name": "newrepo"},
            ],
        )

        # Mock repo validation
        requests_mock.get(
            "https://api.github.com/repos/testowner/existing",
            json={"name": "existing", "owner": {"login": "testowner"}},
        )
        requests_mock.get(
            "https://api.github.com/repos/testowner/newrepo",
            json={"name": "newrepo", "owner": {"login": "testowner"}},
        )

        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--owner",
                "testowner",
                "--output",
                output_pattern,
            ],
        ):
            with mock.patch.object(gh_pr_metrics.state_manager, "_state_file", state_file):
                result = gh_pr_metrics.main()
                assert result == 0

                # Verify state file has both repos (within mock context)
                state = gh_pr_metrics.state_manager.load()
                assert len(state) == 2
                # Existing repo should keep its original csv_file
                assert state["https://github.com/testowner/existing"]["csv_file"] == str(csv_file)

    def test_init_uses_default_start_date(self, requests_mock, tmp_path):
        """Test that init uses default start date when --start not provided."""
        state_file = tmp_path / "state.yaml"
        csv_file = tmp_path / "test.csv"

        # Mock rate limit check at startup
        requests_mock.get(
            "https://api.github.com/rate_limit",
            json={
                "resources": {
                    "core": {
                        "limit": 5000,
                        "remaining": 4999,
                        "reset": 1699999999,
                    }
                }
            },
        )

        # Mock repo validation
        requests_mock.get(
            "https://api.github.com/repos/testowner/testrepo",
            json={"name": "testrepo", "owner": {"login": "testowner"}},
        )

        with mock.patch.object(
            sys,
            "argv",
            [
                "gh-pr-metrics",
                "--init",
                "--owner",
                "testowner",
                "--repo",
                "testrepo",
                "--output",
                str(csv_file),
            ],
        ):
            with mock.patch.object(gh_pr_metrics.state_manager, "_state_file", state_file):
                result = gh_pr_metrics.main()
                assert result == 0

                # Verify state file has a timestamp (should be 365 days ago by default)
                state = gh_pr_metrics.state_manager.load()
                repo_key = "https://github.com/testowner/testrepo"
                assert repo_key in state
                # Just verify timestamp exists and is valid
                timestamp_str = state[repo_key]["timestamp"]
                assert timestamp_str
                gh_pr_metrics.parse_timestamp(timestamp_str)

    """Test expand_output_pattern function."""

    def test_expand_basic_pattern(self):
        """Test basic pattern expansion."""
        result = gh_pr_metrics.expand_output_pattern("data/{owner}-{repo}.csv", "myowner", "myrepo")
        assert result == "data/myowner-myrepo.csv"

    def test_expand_owner_only(self):
        """Test pattern with only owner."""
        result = gh_pr_metrics.expand_output_pattern("{owner}/metrics.csv", "testowner", "testrepo")
        assert result == "testowner/metrics.csv"

    def test_expand_repo_only(self):
        """Test pattern with only repo."""
        result = gh_pr_metrics.expand_output_pattern("data/{repo}.csv", "testowner", "testrepo")
        assert result == "data/testrepo.csv"

    def test_expand_no_placeholders(self):
        """Test pattern without placeholders."""
        result = gh_pr_metrics.expand_output_pattern("data/metrics.csv", "testowner", "testrepo")
        assert result == "data/metrics.csv"

    def test_expand_multiple_occurrences(self):
        """Test pattern with multiple occurrences of same placeholder."""
        result = gh_pr_metrics.expand_output_pattern(
            "{owner}/{owner}-{repo}.csv", "testowner", "testrepo"
        )
        assert result == "testowner/testowner-testrepo.csv"
