# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for utility functions."""

from datetime import datetime, timezone
from unittest import mock

import gh_pr_metrics
import utils


class TestGitHubToken:
    """Test GitHub token retrieval utility."""

    def test_get_github_token_from_env(self):
        """Test getting GitHub token from environment."""
        with mock.patch.dict("os.environ", {"GITHUB_TOKEN": "test_token"}):
            token = gh_pr_metrics.get_github_token()
            assert token == "test_token"

    def test_get_github_token_none_when_not_set(self):
        """Test getting GitHub token when not set."""
        with mock.patch.dict("os.environ", {}, clear=True):
            token = gh_pr_metrics.get_github_token()
            assert token is None


class TestFormatTimestampLocal:
    """Test format_timestamp_local utility function."""

    def test_format_iso_string_with_z_notation(self):
        """Test formatting ISO string with Z notation."""
        # UTC timestamp
        result = utils.format_timestamp_local("2020-02-26T18:03:44Z")

        # Verify format: YYYY-MM-DD HH:MM:SS±HHMM
        assert len(result) == 24  # "2020-02-26 18:03:44+0000" or similar with ± offset
        assert result.startswith("2020-02-26 ")
        assert ":" in result  # Has time separator
        # Should have timezone offset at the end (±HHMM)
        assert result[-5] in ["+", "-"]
        assert result[-4:].isdigit()

    def test_format_iso_string_with_offset_notation(self):
        """Test formatting ISO string with +00:00 notation."""
        result = utils.format_timestamp_local("2020-02-19T19:45:13+00:00")

        # Verify format
        assert len(result) == 24
        assert result.startswith("2020-02-19 ")
        assert ":" in result
        assert result[-5] in ["+", "-"]
        assert result[-4:].isdigit()

    def test_format_datetime_object(self):
        """Test formatting datetime object."""
        dt = datetime(2020, 2, 26, 18, 3, 44, tzinfo=timezone.utc)
        result = utils.format_timestamp_local(dt)

        # Verify format
        assert len(result) == 24
        assert result.startswith("2020-02-26 ")
        assert ":" in result
        assert result[-5] in ["+", "-"]
        assert result[-4:].isdigit()

    def test_format_preserves_timestamp_value(self):
        """Test that formatting preserves the actual timestamp value."""
        # Use a known UTC timestamp and verify conversion
        dt_utc = datetime(2020, 1, 15, 12, 0, 0, tzinfo=timezone.utc)
        result = utils.format_timestamp_local(dt_utc)

        # Parse result back to verify correctness
        from dateutil import parser as date_parser

        parsed = date_parser.parse(result)

        # Should represent the same moment in time
        assert parsed.astimezone(timezone.utc) == dt_utc

    def test_format_consistent_for_same_timestamp(self):
        """Test that different input formats for same timestamp produce same output."""
        # Same timestamp in different formats
        iso_z = "2020-02-26T18:03:44Z"
        iso_offset = "2020-02-26T18:03:44+00:00"
        dt_obj = datetime(2020, 2, 26, 18, 3, 44, tzinfo=timezone.utc)

        result_z = utils.format_timestamp_local(iso_z)
        result_offset = utils.format_timestamp_local(iso_offset)
        result_dt = utils.format_timestamp_local(dt_obj)

        # All should produce identical output
        assert result_z == result_offset == result_dt
