# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for --wait functionality."""

from datetime import datetime, timezone
from unittest import mock

import gh_pr_metrics


def test_wait_for_quota_reset_sleeps_correct_duration():
    """Test that wait_for_quota_reset calculates and sleeps for correct duration."""
    # Set reset time to 5 minutes from now
    now = datetime.now(timezone.utc)
    reset_time = now.timestamp() + (5 * 60)  # 5 minutes = 300 seconds

    # Set global reset timestamp (already includes +15 second buffer in actual code)
    gh_pr_metrics._api_quota_reset = int(reset_time)

    # Mock time.sleep to avoid actually waiting
    with mock.patch("time.sleep") as mock_sleep:
        result = gh_pr_metrics.wait_for_quota_reset()

    # Should return True (success)
    assert result is True

    # Should have called sleep once
    assert mock_sleep.call_count == 1

    # Should sleep for approximately 300 + 15 seconds (5 min + buffer)
    # Allow some variance for test execution time
    sleep_duration = mock_sleep.call_args[0][0]
    assert 310 < sleep_duration < 320, f"Expected ~315 seconds, got {sleep_duration}"


def test_wait_for_quota_reset_handles_no_reset_timestamp():
    """Test that wait handles uninitialized reset timestamp."""
    # Reset global to uninitialized (0 + 15 buffer = 15, which is in the past)
    gh_pr_metrics._api_quota_reset = 0

    with mock.patch("time.sleep") as mock_sleep:
        result = gh_pr_metrics.wait_for_quota_reset()

    # Should return True (treats as "already reset" since timestamp is in the past)
    assert result is True
    # Should not sleep (timestamp is way in the past)
    assert mock_sleep.call_count == 0


def test_wait_for_quota_reset_already_reset():
    """Test that wait returns immediately if quota already reset."""
    # Set reset time to the past
    past_time = datetime.now(timezone.utc).timestamp() - 60  # 1 minute ago
    gh_pr_metrics._api_quota_reset = int(past_time)

    with mock.patch("time.sleep") as mock_sleep:
        result = gh_pr_metrics.wait_for_quota_reset()

    # Should return True (success)
    assert result is True

    # Should NOT have slept (already reset)
    assert mock_sleep.call_count == 0
