# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for repository detection from git."""

from unittest import mock
import subprocess

import gh_pr_metrics


class TestRepoDetection:
    """Test repository detection from git config."""

    def test_get_repo_from_git_ssh_url(self):
        """Test parsing SSH git URL."""
        with mock.patch("subprocess.check_output") as mock_subprocess:
            mock_subprocess.return_value = "git@github.com:testowner/testrepo.git\n"
            owner, repo = gh_pr_metrics.get_repo_from_git()
            assert owner == "testowner"
            assert repo == "testrepo"

    def test_get_repo_from_git_https_url(self):
        """Test parsing HTTPS git URL."""
        with mock.patch("subprocess.check_output") as mock_subprocess:
            mock_subprocess.return_value = "https://github.com/testowner/testrepo.git\n"
            owner, repo = gh_pr_metrics.get_repo_from_git()
            assert owner == "testowner"
            assert repo == "testrepo"

    def test_get_repo_from_git_without_git_extension(self):
        """Test parsing git URL without .git extension."""
        with mock.patch("subprocess.check_output") as mock_subprocess:
            mock_subprocess.return_value = "https://github.com/testowner/testrepo\n"
            owner, repo = gh_pr_metrics.get_repo_from_git()
            assert owner == "testowner"
            assert repo == "testrepo"

    def test_get_repo_from_git_failure(self):
        """Test handling when git command fails."""
        with mock.patch("subprocess.check_output") as mock_subprocess:
            mock_subprocess.side_effect = subprocess.CalledProcessError(1, "git")
            owner, repo = gh_pr_metrics.get_repo_from_git()
            assert owner is None
            assert repo is None

    def test_get_repo_from_git_invalid_url(self):
        """Test handling of invalid git URL."""
        with mock.patch("subprocess.check_output") as mock_subprocess:
            mock_subprocess.return_value = "invalid-url\n"
            owner, repo = gh_pr_metrics.get_repo_from_git()
            assert owner is None
            assert repo is None
