# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for command-line argument parsing."""

from unittest import mock
import sys

# Import the module to test
import gh_pr_metrics


class TestArgumentParsing:
    """Test argument parsing functionality."""

    def test_parse_arguments_minimal(self):
        """Test parsing with no arguments."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.owner is None
            assert args.repo is None
            assert args.start is None
            assert args.end is None
            assert args.output is None
            assert args.debug is False

    def test_parse_arguments_with_owner_and_repo(self):
        """Test parsing with owner and repo specified."""
        with mock.patch.object(
            sys, "argv", ["gh-pr-metrics", "--owner", "testowner", "--repo", "testrepo"]
        ):
            args = gh_pr_metrics.parse_arguments()
            assert args.owner == "testowner"
            assert args.repo == "testrepo"

    def test_parse_arguments_with_debug(self):
        """Test parsing with debug flag."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics", "--debug"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.debug is True

    def test_parse_arguments_with_output(self):
        """Test parsing with output file specified."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics", "--output", "test.csv"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.output == "test.csv"

    def test_parse_arguments_with_time_range(self):
        """Test parsing with start and end timestamps."""
        with mock.patch.object(
            sys, "argv", ["gh-pr-metrics", "--start", "2024-01-01", "--end", "2024-12-31"]
        ):
            args = gh_pr_metrics.parse_arguments()
            assert args.start == "2024-01-01"
            assert args.end == "2024-12-31"

    def test_parse_arguments_with_workers(self):
        """Test parsing with workers argument."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics", "--workers", "8"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.workers == 8

    def test_parse_arguments_workers_default(self):
        """Test that workers defaults to 4."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.workers == 4

    def test_parse_arguments_ai_bot_regex_default(self):
        """Test that ai-bot-regex has a default value."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.ai_bot_regex == "cursor\\[bot\\]"

    def test_parse_arguments_with_ai_bot_regex(self):
        """Test parsing with custom ai-bot-regex."""
        with mock.patch.object(
            sys, "argv", ["gh-pr-metrics", "--ai-bot-regex", "copilot\\[bot\\]|cursor\\[bot\\]"]
        ):
            args = gh_pr_metrics.parse_arguments()
            assert args.ai_bot_regex == "copilot\\[bot\\]|cursor\\[bot\\]"

    def test_parse_arguments_with_update(self):
        """Test parsing with update flag."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics", "--update"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.update is True

    def test_parse_arguments_update_default(self):
        """Test that update defaults to False."""
        with mock.patch.object(sys, "argv", ["gh-pr-metrics"]):
            args = gh_pr_metrics.parse_arguments()
            assert args.update is False


class TestLoggingSetup:
    """Test logging configuration."""

    def test_setup_logging_default(self):
        """Test logging setup with default (non-debug) mode."""
        gh_pr_metrics.setup_logging(debug=False)
        # Just verify it doesn't crash
        assert True

    def test_setup_logging_debug(self):
        """Test logging setup with debug mode."""
        gh_pr_metrics.setup_logging(debug=True)
        # Just verify it doesn't crash
        assert True
