# Generated By: Cursor (Claude Sonnet 4.5)
"""Tests for pull request processing logic."""

import gh_pr_metrics


class TestPRStatusDetermination:
    """Test PR status determination logic."""

    def test_determine_draft_status(self):
        """Test identifying draft PRs."""
        pr = {"draft": True, "state": "open", "merged_at": None}
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "draft"

    def test_determine_merged_status(self, requests_mock):
        """Test identifying merged PRs and extracting merge timestamp."""
        pr = {
            "number": 1,
            "title": "Merged PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "merged_at": "2024-01-05T12:00:00Z",
            "closed_at": "2024-01-05T12:00:00Z",
            "created_at": "2024-01-01T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Test status determination
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "merged"

        # Test full PR processing extracts timestamps
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(reviews_url, json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)
        assert result["merged_at"] == "2024-01-05T12:00:00Z"
        assert result["closed_at"] == "2024-01-05T12:00:00Z"
        assert result["status"] == "merged"

    def test_determine_closed_status(self, requests_mock):
        """Test identifying closed (not merged) PRs and extracting close timestamp."""
        pr = {
            "number": 2,
            "title": "Closed PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "merged_at": None,
            "closed_at": "2024-01-10T15:30:00Z",
            "created_at": "2024-01-08T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/2",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/2/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/2/comments",
        }

        # Test status determination
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "closed"

        # Test full PR processing extracts timestamps
        events_url = "https://api.github.com/repos/owner/repo/issues/2/events"
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/2/reviews"
        requests_mock.get(events_url, json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get(reviews_url, json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)
        assert result["merged_at"] == ""  # Not merged
        assert result["closed_at"] == "2024-01-10T15:30:00Z"
        assert result["status"] == "closed"

    def test_determine_open_status(self):
        """Test identifying open PRs."""
        pr = {"draft": False, "state": "open", "merged_at": None}
        status = gh_pr_metrics.determine_pr_status(pr)
        assert status == "open"


class TestReadyForReviewTime:
    """Test ready for review timestamp determination."""

    def test_ready_for_review_never_draft(self, requests_mock):
        """Test PR that was never a draft."""
        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return no ready_for_review events
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(events_url, json=[])

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-01T00:00:00Z"

    def test_ready_for_review_with_event(self, requests_mock):
        """Test PR that was converted from draft."""
        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return ready_for_review event
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(
            events_url,
            json=[{"event": "ready_for_review", "created_at": "2024-01-02T00:00:00Z"}],
        )

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        assert result == "2024-01-02T00:00:00Z"

    def test_ready_for_review_api_error(self, requests_mock):
        """Test handling API errors when fetching events."""
        pr = {
            "number": 1,
            "draft": False,
            "created_at": "2024-01-01T00:00:00Z",
        }

        # Mock the events API to return error
        events_url = "https://api.github.com/repos/owner/repo/issues/1/events"
        requests_mock.get(events_url, status_code=500)

        result = gh_pr_metrics.get_ready_for_review_time(pr, "owner", "repo", None)
        # Should fall back to created_at
        assert result == "2024-01-01T00:00:00Z"


class TestCommentCounting:
    """Test comment counting logic."""

    def test_count_comments_no_comments(self, requests_mock):
        """Test counting when there are no comments."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = gh_pr_metrics.count_comments(
            pr, "owner", "repo", None, "cursor\\[bot\\]"
        )
        assert total == 0
        assert non_ai_bot == 0
        assert ai_bot == 0
        assert non_ai_bot_names == ""
        assert ai_bot_names == ""

    def test_count_comments_with_regular_comments(self, requests_mock):
        """Test counting regular comments."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "User", "login": "user1"}},
                {"user": {"type": "User", "login": "user2"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"], json=[{"user": {"type": "User", "login": "user3"}}]
        )

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = gh_pr_metrics.count_comments(
            pr, "owner", "repo", None, "cursor\\[bot\\]"
        )
        assert total == 3
        assert non_ai_bot == 0
        assert ai_bot == 0
        assert non_ai_bot_names == ""
        assert ai_bot_names == ""

    def test_count_comments_with_bot_comments(self, requests_mock):
        """Test counting bot comments separately."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "Bot", "login": "github-actions[bot]"}},
                {"user": {"type": "User", "login": "user1"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"], json=[{"user": {"type": "Bot", "login": "dependabot[bot]"}}]
        )

        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = gh_pr_metrics.count_comments(
            pr, "owner", "repo", None, "cursor\\[bot\\]"
        )
        assert total == 3
        assert non_ai_bot == 2
        assert ai_bot == 0
        assert non_ai_bot_names == "dependabot[bot],github-actions[bot]"
        assert ai_bot_names == ""

    def test_count_comments_with_ai_bot_comments(self, requests_mock):
        """Test counting AI bot comments separately."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "Bot", "login": "cursor[bot]"}},
                {"user": {"type": "Bot", "login": "github-actions[bot]"}},
                {"user": {"type": "User", "login": "user1"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"], json=[{"user": {"type": "Bot", "login": "cursor[bot]"}}]
        )

        # Test with default CLI pattern
        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = gh_pr_metrics.count_comments(
            pr, "owner", "repo", None, "cursor\\[bot\\]"
        )
        assert total == 4
        assert non_ai_bot == 1
        assert ai_bot == 2
        assert non_ai_bot_names == "github-actions[bot]"
        assert ai_bot_names == "cursor[bot]"

    def test_count_comments_with_none_ai_bot_pattern(self, requests_mock):
        """Test that None ai_bot_pattern treats all bots as non-AI bots."""
        pr = {
            "number": 1,
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        requests_mock.get(
            pr["comments_url"],
            json=[
                {"user": {"type": "Bot", "login": "cursor[bot]"}},
                {"user": {"type": "Bot", "login": "github-actions[bot]"}},
                {"user": {"type": "User", "login": "user1"}},
            ],
        )
        requests_mock.get(
            pr["review_comments_url"], json=[{"user": {"type": "Bot", "login": "cursor[bot]"}}]
        )

        # Test with None pattern - all bots should be non-AI
        total, non_ai_bot, ai_bot, non_ai_bot_names, ai_bot_names = gh_pr_metrics.count_comments(
            pr, "owner", "repo", None, None
        )
        assert total == 4
        assert non_ai_bot == 3  # All bots are non-AI when pattern is None
        assert ai_bot == 0
        assert non_ai_bot_names == "cursor[bot],github-actions[bot]"
        assert ai_bot_names == ""


class TestReviewMetrics:
    """Test review metrics calculation."""

    def test_get_review_metrics_no_reviews(self, requests_mock):
        """Test when there are no reviews."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(reviews_url, json=[])

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 0
        assert unique == 0
        assert approvals == 0

    def test_get_review_metrics_with_changes_requested(self, requests_mock):
        """Test counting change requests."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer2"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 3  # Total count
        assert unique == 2  # Unique reviewers
        assert approvals == 0

    def test_get_review_metrics_with_approvals(self, requests_mock):
        """Test counting approvals."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "APPROVED"},
                {"user": {"login": "reviewer2"}, "state": "APPROVED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 0
        assert unique == 0
        assert approvals == 2

    def test_get_review_metrics_reviewer_changes_state(self, requests_mock):
        """Test when reviewer changes their review state."""
        pr = {"number": 1}
        reviews_url = "https://api.github.com/repos/owner/repo/pulls/1/reviews"
        requests_mock.get(
            reviews_url,
            json=[
                {"user": {"login": "reviewer1"}, "state": "CHANGES_REQUESTED"},
                {"user": {"login": "reviewer1"}, "state": "APPROVED"},
            ],
        )

        changes, unique, approvals = gh_pr_metrics.get_review_metrics(pr, "owner", "repo", None)
        assert changes == 1  # Total change requests
        assert unique == 1  # Unique reviewer who requested changes
        assert approvals == 1  # Most recent state is approved


class TestDerivedTimeMetrics:
    """Test derived time metrics (days_open, days_in_review)."""

    def test_days_open_for_merged_pr(self, requests_mock):
        """Test days_open calculation for merged PR."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": "2024-01-11T00:00:00Z",  # 10 days later
            "closed_at": "2024-01-11T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API calls
        requests_mock.get("https://api.github.com/repos/owner/repo/issues/1/events", json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get("https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)

        assert result["days_open"] == 10.0
        assert result["days_in_review"] == 10.0  # Never draft, so same as days_open

    def test_days_in_review_excludes_draft_time(self, requests_mock):
        """Test that days_in_review excludes draft period."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "closed",
            "created_at": "2024-01-01T00:00:00Z",
            "merged_at": "2024-01-11T00:00:00Z",
            "closed_at": "2024-01-11T00:00:00Z",
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock ready_for_review event (marked ready 3 days after creation)
        requests_mock.get(
            "https://api.github.com/repos/owner/repo/issues/1/events",
            json=[{"event": "ready_for_review", "created_at": "2024-01-04T00:00:00Z"}],
        )
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get("https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)

        assert result["days_open"] == 10.0  # Jan 1 → Jan 11
        assert result["days_in_review"] == 7.0  # Jan 4 (ready) → Jan 11

    def test_days_open_for_open_pr(self, requests_mock):
        """Test days_open calculation uses current time for open PRs."""
        from datetime import datetime, timezone

        # PR created 5 days ago
        now = datetime.now(timezone.utc)
        from datetime import timedelta

        created = now - timedelta(days=5)

        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": created.isoformat(),
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API calls
        requests_mock.get("https://api.github.com/repos/owner/repo/issues/1/events", json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get("https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)

        # Should be approximately 5 days (allow small variance for test execution time)
        assert 4.99 <= result["days_open"] <= 5.01
        assert 4.99 <= result["days_in_review"] <= 5.01

    def test_days_metrics_handle_errors_gracefully(self, requests_mock):
        """Test that time metrics handle missing/invalid timestamps gracefully."""
        pr = {
            "number": 1,
            "title": "Test PR",
            "user": {"login": "testuser"},
            "draft": False,
            "state": "open",
            "created_at": "invalid-date",  # Invalid timestamp
            "merged_at": None,
            "closed_at": None,
            "html_url": "https://github.com/owner/repo/pull/1",
            "comments_url": "https://api.github.com/repos/owner/repo/issues/1/comments",
            "review_comments_url": "https://api.github.com/repos/owner/repo/pulls/1/comments",
        }

        # Mock API calls
        requests_mock.get("https://api.github.com/repos/owner/repo/issues/1/events", json=[])
        requests_mock.get(pr["comments_url"], json=[])
        requests_mock.get(pr["review_comments_url"], json=[])
        requests_mock.get("https://api.github.com/repos/owner/repo/pulls/1/reviews", json=[])

        result = gh_pr_metrics.process_pr(pr, "owner", "repo", None)

        # Should have empty strings for time metrics
        assert result["days_open"] == ""
        assert result["days_in_review"] == ""
        assert "time_metrics" in result["errors"]
